// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dendra/modelregistry/v1/model.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Model — un modèle d'inférence AUTORISÉ on-chain (attestation gouvernée).
// Le `weights_sha256` est l'ancre de confiance : la chaîne ne paie que de l'inférence
// dont le modèle servi correspond à un Model enregistré + actif (application côté x/jobs).
type Model struct {
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WeightsSha256 string `protobuf:"bytes,2,opt,name=weights_sha256,json=weightsSha256,proto3" json:"weights_sha256,omitempty"`
	Quant         string `protobuf:"bytes,3,opt,name=quant,proto3" json:"quant,omitempty"`
	Engine        string `protobuf:"bytes,4,opt,name=engine,proto3" json:"engine,omitempty"`
	HwClass       string `protobuf:"bytes,5,opt,name=hw_class,json=hwClass,proto3" json:"hw_class,omitempty"`
	Active        bool   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	// INT-8 — ancrage Hugging Face (optionnel) : identité de modèle REPRODUCTIBLE + auditable.
	HfRepo     string `protobuf:"bytes,7,opt,name=hf_repo,json=hfRepo,proto3" json:"hf_repo,omitempty"`
	HfRevision string `protobuf:"bytes,8,opt,name=hf_revision,json=hfRevision,proto3" json:"hf_revision,omitempty"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_abed52bdb1ab8d16, []int{0}
}
func (m *Model) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Model.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return m.Size()
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Model) GetWeightsSha256() string {
	if m != nil {
		return m.WeightsSha256
	}
	return ""
}

func (m *Model) GetQuant() string {
	if m != nil {
		return m.Quant
	}
	return ""
}

func (m *Model) GetEngine() string {
	if m != nil {
		return m.Engine
	}
	return ""
}

func (m *Model) GetHwClass() string {
	if m != nil {
		return m.HwClass
	}
	return ""
}

func (m *Model) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Model) GetHfRepo() string {
	if m != nil {
		return m.HfRepo
	}
	return ""
}

func (m *Model) GetHfRevision() string {
	if m != nil {
		return m.HfRevision
	}
	return ""
}

func init() {
	proto.RegisterType((*Model)(nil), "dendra.modelregistry.v1.Model")
}

func init() {
	proto.RegisterFile("dendra/modelregistry/v1/model.proto", fileDescriptor_abed52bdb1ab8d16)
}

var fileDescriptor_abed52bdb1ab8d16 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0xeb, 0x40, 0x7e, 0x30, 0xa2, 0x83, 0x55, 0x51, 0x83, 0x90, 0xa9, 0x40, 0x48, 0x9d,
	0x12, 0x15, 0x44, 0x1f, 0x00, 0x66, 0x96, 0xb0, 0xb1, 0x44, 0xa1, 0xb9, 0x8d, 0x2d, 0x95, 0x38,
	0xc4, 0x26, 0xa1, 0x6f, 0xc1, 0x63, 0x31, 0x76, 0x84, 0x0d, 0x25, 0x2f, 0x82, 0x62, 0x67, 0x81,
	0xcd, 0xe7, 0x7c, 0x9f, 0xef, 0x70, 0xf0, 0x65, 0x06, 0x45, 0x56, 0xa5, 0xd1, 0x8b, 0xcc, 0x60,
	0x53, 0x41, 0x2e, 0x94, 0xae, 0xb6, 0x51, 0xbd, 0xb0, 0x45, 0x58, 0x56, 0x52, 0x4b, 0x32, 0xb5,
	0x52, 0xf8, 0x47, 0x0a, 0xeb, 0xc5, 0xe9, 0x24, 0x97, 0xb9, 0x34, 0x4e, 0xd4, 0xbf, 0xac, 0x7e,
	0xf1, 0x8d, 0xb0, 0xfb, 0xd0, 0xab, 0x64, 0x8c, 0x1d, 0x91, 0x51, 0x34, 0x43, 0xf3, 0x83, 0xd8,
	0x11, 0x19, 0xb9, 0xc2, 0xe3, 0x06, 0x44, 0xce, 0xb5, 0x4a, 0x14, 0x4f, 0xaf, 0x6f, 0x97, 0xd4,
	0x31, 0xec, 0x68, 0x68, 0x1f, 0x4d, 0x49, 0x26, 0xd8, 0x7d, 0x7d, 0x4b, 0x0b, 0x4d, 0xf7, 0x0c,
	0xb5, 0x81, 0x1c, 0x63, 0x0f, 0x8a, 0x5c, 0x14, 0x40, 0xf7, 0x4d, 0x3d, 0x24, 0x72, 0x82, 0x03,
	0xde, 0x24, 0xab, 0x4d, 0xaa, 0x14, 0x75, 0x0d, 0xf1, 0x79, 0x73, 0xdf, 0xc7, 0xfe, 0x4b, 0xba,
	0xd2, 0xa2, 0x06, 0xea, 0xcd, 0xd0, 0x3c, 0x88, 0x87, 0x44, 0xa6, 0xd8, 0xe7, 0xeb, 0xa4, 0x82,
	0x52, 0x52, 0xdf, 0xde, 0xe2, 0xeb, 0x18, 0x4a, 0x49, 0xce, 0xf1, 0xa1, 0x01, 0xb5, 0x50, 0x42,
	0x16, 0x34, 0x30, 0x10, 0xf7, 0xd0, 0x36, 0x77, 0xcb, 0xcf, 0x96, 0xa1, 0x5d, 0xcb, 0xd0, 0x4f,
	0xcb, 0xd0, 0x47, 0xc7, 0x46, 0xbb, 0x8e, 0x8d, 0xbe, 0x3a, 0x36, 0x7a, 0x3a, 0x1b, 0x96, 0x7c,
	0xff, 0xb7, 0xa5, 0xde, 0x96, 0xa0, 0x9e, 0x3d, 0x33, 0xcd, 0xcd, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xce, 0x53, 0xc4, 0x3d, 0x70, 0x01, 0x00, 0x00,
}

func (m *Model) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Model) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Model) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HfRevision) > 0 {
		i -= len(m.HfRevision)
		copy(dAtA[i:], m.HfRevision)
		i = encodeVarintModel(dAtA, i, uint64(len(m.HfRevision)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.HfRepo) > 0 {
		i -= len(m.HfRepo)
		copy(dAtA[i:], m.HfRepo)
		i = encodeVarintModel(dAtA, i, uint64(len(m.HfRepo)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.HwClass) > 0 {
		i -= len(m.HwClass)
		copy(dAtA[i:], m.HwClass)
		i = encodeVarintModel(dAtA, i, uint64(len(m.HwClass)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Engine) > 0 {
		i -= len(m.Engine)
		copy(dAtA[i:], m.Engine)
		i = encodeVarintModel(dAtA, i, uint64(len(m.Engine)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Quant) > 0 {
		i -= len(m.Quant)
		copy(dAtA[i:], m.Quant)
		i = encodeVarintModel(dAtA, i, uint64(len(m.Quant)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.WeightsSha256) > 0 {
		i -= len(m.WeightsSha256)
		copy(dAtA[i:], m.WeightsSha256)
		i = encodeVarintModel(dAtA, i, uint64(len(m.WeightsSha256)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintModel(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintModel(dAtA []byte, offset int, v uint64) int {
	offset -= sovModel(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Model) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.WeightsSha256)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.Quant)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.Engine)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.HwClass)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	if m.Active {
		n += 2
	}
	l = len(m.HfRepo)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.HfRevision)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	return n
}

func sovModel(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozModel(x uint64) (n int) {
	return sovModel(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Model) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Model: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Model: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WeightsSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WeightsSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Quant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Engine", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Engine = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HwClass", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HwClass = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HfRepo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HfRepo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HfRevision", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HfRevision = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipModel(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowModel
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthModel
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupModel
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthModel
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthModel        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowModel          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupModel = fmt.Errorf("proto: unexpected end of group")
)
