// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dendra/jobs/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the jobs module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params    Params   `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	MinerMap  []Miner  `protobuf:"bytes,2,rep,name=miner_map,json=minerMap,proto3" json:"miner_map"`
	JobMap    []Job    `protobuf:"bytes,3,rep,name=job_map,json=jobMap,proto3" json:"job_map"`
	Pools     *Pools   `protobuf:"bytes,4,opt,name=pools,proto3" json:"pools,omitempty"`
	CommitMap []Commit `protobuf:"bytes,5,rep,name=commit_map,json=commitMap,proto3" json:"commit_map"`
	BeaconMap []Beacon `protobuf:"bytes,6,rep,name=beacon_map,json=beaconMap,proto3" json:"beacon_map"`
	// VALEUR. Fee et burn RETENUS par job (fee-hold v2). Les coins restent au compte de module, mais
	// sans ces deux tables plus rien ne dit à QUI ils reviennent ni quand les libérer : fonds orphelins.
	HeldFee  []HeldAmount `protobuf:"bytes,7,rep,name=held_fee,json=heldFee,proto3" json:"held_fee"`
	HeldBurn []HeldAmount `protobuf:"bytes,8,rep,name=held_burn,json=heldBurn,proto3" json:"held_burn"`
	// ÉCHÉANCES. Chaque entrée est un rendez-vous que l'EndBlocker doit honorer. Les perdre ne perd pas
	// des coins directement — c'est pire : les jobs concernés ne se résolvent JAMAIS, donc leur escrow
	// et leur rétention restent bloqués sans qu'aucune erreur ne soit levée.
	PendingReveal        []PendingEntry `protobuf:"bytes,9,rep,name=pending_reveal,json=pendingReveal,proto3" json:"pending_reveal"`
	PendingAudit         []PendingEntry `protobuf:"bytes,10,rep,name=pending_audit,json=pendingAudit,proto3" json:"pending_audit"`
	PendingAuditResolve  []PendingEntry `protobuf:"bytes,11,rep,name=pending_audit_resolve,json=pendingAuditResolve,proto3" json:"pending_audit_resolve"`
	PendingAppealResolve []PendingEntry `protobuf:"bytes,12,rep,name=pending_appeal_resolve,json=pendingAppealResolve,proto3" json:"pending_appeal_resolve"`
	// AUTORISATION. Comité d'audit ancré (ADR-032/033) : qui a le droit de voter. Absent, le tally est
	// fail-closed — sûr, mais toute dispute en vol devient inerte.
	AuditCommittee []StringEntry `protobuf:"bytes,13,rep,name=audit_committee,json=auditCommittee,proto3" json:"audit_committee"`
	// Clés VRF des validateurs : sans elles, aucun contributeur à la graine -> anti-grinding INACTIF
	// jusqu'à ce que chacun ré-ancre. Visible dans les logs, mais silencieux côté état.
	ValidatorVrfPubkey []StringEntry `protobuf:"bytes,14,rep,name=validator_vrf_pubkey,json=validatorVrfPubkey,proto3" json:"validator_vrf_pubkey"`
	// ANTI-ABUS. Probation Sybil : remise à zéro, un mineur déjà connu repart avec un compteur neuf.
	MinerOptimisticCount []Uint64Entry `protobuf:"bytes,15,rep,name=miner_optimistic_count,json=minerOptimisticCount,proto3" json:"miner_optimistic_count"`
	// Fenêtre glissante d'échecs de disponibilité : la perdre efface l'historique qui arme le slash.
	AvailFailCount       []Uint64Entry `protobuf:"bytes,16,rep,name=avail_fail_count,json=availFailCount,proto3" json:"avail_fail_count"`
	AvailFailWindowStart []Uint64Entry `protobuf:"bytes,17,rep,name=avail_fail_window_start,json=availFailWindowStart,proto3" json:"avail_fail_window_start"`
	// Défi de disponibilité courant (les présences prouvées, elles, sont per-époque : cf. `reserved 19`).
	AvailChallenge string `protobuf:"bytes,18,opt,name=avail_challenge,json=availChallenge,proto3" json:"avail_challenge,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7af7667158ffbf, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetMinerMap() []Miner {
	if m != nil {
		return m.MinerMap
	}
	return nil
}

func (m *GenesisState) GetJobMap() []Job {
	if m != nil {
		return m.JobMap
	}
	return nil
}

func (m *GenesisState) GetPools() *Pools {
	if m != nil {
		return m.Pools
	}
	return nil
}

func (m *GenesisState) GetCommitMap() []Commit {
	if m != nil {
		return m.CommitMap
	}
	return nil
}

func (m *GenesisState) GetBeaconMap() []Beacon {
	if m != nil {
		return m.BeaconMap
	}
	return nil
}

func (m *GenesisState) GetHeldFee() []HeldAmount {
	if m != nil {
		return m.HeldFee
	}
	return nil
}

func (m *GenesisState) GetHeldBurn() []HeldAmount {
	if m != nil {
		return m.HeldBurn
	}
	return nil
}

func (m *GenesisState) GetPendingReveal() []PendingEntry {
	if m != nil {
		return m.PendingReveal
	}
	return nil
}

func (m *GenesisState) GetPendingAudit() []PendingEntry {
	if m != nil {
		return m.PendingAudit
	}
	return nil
}

func (m *GenesisState) GetPendingAuditResolve() []PendingEntry {
	if m != nil {
		return m.PendingAuditResolve
	}
	return nil
}

func (m *GenesisState) GetPendingAppealResolve() []PendingEntry {
	if m != nil {
		return m.PendingAppealResolve
	}
	return nil
}

func (m *GenesisState) GetAuditCommittee() []StringEntry {
	if m != nil {
		return m.AuditCommittee
	}
	return nil
}

func (m *GenesisState) GetValidatorVrfPubkey() []StringEntry {
	if m != nil {
		return m.ValidatorVrfPubkey
	}
	return nil
}

func (m *GenesisState) GetMinerOptimisticCount() []Uint64Entry {
	if m != nil {
		return m.MinerOptimisticCount
	}
	return nil
}

func (m *GenesisState) GetAvailFailCount() []Uint64Entry {
	if m != nil {
		return m.AvailFailCount
	}
	return nil
}

func (m *GenesisState) GetAvailFailWindowStart() []Uint64Entry {
	if m != nil {
		return m.AvailFailWindowStart
	}
	return nil
}

func (m *GenesisState) GetAvailChallenge() string {
	if m != nil {
		return m.AvailChallenge
	}
	return ""
}

// HeldAmount — montant retenu pour un job (fee-hold v2).
type HeldAmount struct {
	JobId  string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Amount uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *HeldAmount) Reset()         { *m = HeldAmount{} }
func (m *HeldAmount) String() string { return proto.CompactTextString(m) }
func (*HeldAmount) ProtoMessage()    {}
func (*HeldAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7af7667158ffbf, []int{1}
}
func (m *HeldAmount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HeldAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HeldAmount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HeldAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeldAmount.Merge(m, src)
}
func (m *HeldAmount) XXX_Size() int {
	return m.Size()
}
func (m *HeldAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_HeldAmount.DiscardUnknown(m)
}

var xxx_messageInfo_HeldAmount proto.InternalMessageInfo

func (m *HeldAmount) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *HeldAmount) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// PendingEntry — un rendez-vous d'un KeySet indexé par paire (hauteur, identifiant).
//
// ⚠️ `blocks_remaining` est RELATIF, pas une hauteur absolue. Les collections indexées par hauteur
// ne sont pas transportées parce que les hauteurs repartent à zéro au genesis ; la même raison
// s'applique ici. Une échéance exportée en absolu se
// déclencherait des milliers de blocs trop tard sur une chaîne relancée à 1, et JAMAIS si la reprise
// se fait au-dessus d'elle — l'EndBlocker matche la hauteur exacte (`NewPrefixedPairRange(h)`). On
// transporte donc le TEMPS QU'IL RESTE À ATTENDRE, que l'import ré-ancre sur la hauteur de reprise.
type PendingEntry struct {
	BlocksRemaining int64  `protobuf:"varint,1,opt,name=blocks_remaining,json=blocksRemaining,proto3" json:"blocks_remaining,omitempty"`
	Id              string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *PendingEntry) Reset()         { *m = PendingEntry{} }
func (m *PendingEntry) String() string { return proto.CompactTextString(m) }
func (*PendingEntry) ProtoMessage()    {}
func (*PendingEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7af7667158ffbf, []int{2}
}
func (m *PendingEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingEntry.Merge(m, src)
}
func (m *PendingEntry) XXX_Size() int {
	return m.Size()
}
func (m *PendingEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PendingEntry proto.InternalMessageInfo

func (m *PendingEntry) GetBlocksRemaining() int64 {
	if m != nil {
		return m.BlocksRemaining
	}
	return 0
}

func (m *PendingEntry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// StringEntry / Uint64Entry — entrées génériques d'une Map clé-chaîne.
type StringEntry struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *StringEntry) Reset()         { *m = StringEntry{} }
func (m *StringEntry) String() string { return proto.CompactTextString(m) }
func (*StringEntry) ProtoMessage()    {}
func (*StringEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7af7667158ffbf, []int{3}
}
func (m *StringEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StringEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StringEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StringEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringEntry.Merge(m, src)
}
func (m *StringEntry) XXX_Size() int {
	return m.Size()
}
func (m *StringEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_StringEntry.DiscardUnknown(m)
}

var xxx_messageInfo_StringEntry proto.InternalMessageInfo

func (m *StringEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StringEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Uint64Entry struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value uint64 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Uint64Entry) Reset()         { *m = Uint64Entry{} }
func (m *Uint64Entry) String() string { return proto.CompactTextString(m) }
func (*Uint64Entry) ProtoMessage()    {}
func (*Uint64Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7af7667158ffbf, []int{4}
}
func (m *Uint64Entry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Uint64Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Uint64Entry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Uint64Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uint64Entry.Merge(m, src)
}
func (m *Uint64Entry) XXX_Size() int {
	return m.Size()
}
func (m *Uint64Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Uint64Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Uint64Entry proto.InternalMessageInfo

func (m *Uint64Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Uint64Entry) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "dendra.jobs.v1.GenesisState")
	proto.RegisterType((*HeldAmount)(nil), "dendra.jobs.v1.HeldAmount")
	proto.RegisterType((*PendingEntry)(nil), "dendra.jobs.v1.PendingEntry")
	proto.RegisterType((*StringEntry)(nil), "dendra.jobs.v1.StringEntry")
	proto.RegisterType((*Uint64Entry)(nil), "dendra.jobs.v1.Uint64Entry")
}

func init() { proto.RegisterFile("dendra/jobs/v1/genesis.proto", fileDescriptor_ec7af7667158ffbf) }

var fileDescriptor_ec7af7667158ffbf = []byte{
	// 778 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x95, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0xc0, 0xe3, 0xfc, 0x6b, 0xfc, 0x92, 0x4d, 0xb2, 0x93, 0x34, 0x58, 0xd9, 0x55, 0x88, 0x72,
	0x21, 0x80, 0x48, 0xb4, 0xe5, 0x8f, 0x40, 0x15, 0x87, 0x4d, 0xc4, 0x2e, 0x2d, 0x5a, 0x51, 0x39,
	0x62, 0x5b, 0x71, 0xb1, 0xc6, 0xf1, 0x24, 0x9d, 0xd4, 0x9e, 0xb1, 0x6c, 0xc7, 0xa5, 0xdf, 0x82,
	0x8f, 0xc1, 0x91, 0x8f, 0xd1, 0x63, 0x8f, 0x9c, 0x10, 0x6a, 0x0f, 0x5c, 0xf9, 0x08, 0x68, 0x66,
	0xec, 0x90, 0xba, 0xad, 0xc8, 0xc5, 0xb2, 0xe7, 0xbd, 0xdf, 0xef, 0xbd, 0x19, 0x8f, 0x3d, 0xf0,
	0xd2, 0x21, 0xcc, 0x09, 0xf0, 0x78, 0xc5, 0xed, 0x70, 0x1c, 0xbf, 0x1a, 0x2f, 0x09, 0x23, 0x21,
	0x0d, 0x47, 0x7e, 0xc0, 0x23, 0x8e, 0xea, 0x2a, 0x3a, 0x12, 0xd1, 0x51, 0xfc, 0xaa, 0xfb, 0x1c,
	0x7b, 0x94, 0xf1, 0xb1, 0xbc, 0xaa, 0x94, 0xee, 0x8b, 0x8c, 0xc0, 0x26, 0x78, 0xce, 0xd9, 0x13,
	0xc1, 0x39, 0xf7, 0x3c, 0x1a, 0x25, 0x41, 0x23, 0x13, 0x5c, 0x71, 0x3b, 0x89, 0x74, 0x33, 0x11,
	0x8f, 0x32, 0x12, 0x3c, 0xa1, 0xf4, 0x71, 0x80, 0xbd, 0xf0, 0x09, 0xd0, 0xe7, 0xdc, 0x4d, 0x63,
	0xed, 0x25, 0x5f, 0x72, 0x79, 0x3b, 0x16, 0x77, 0x6a, 0x74, 0xf0, 0x8f, 0x0e, 0xb5, 0xb7, 0x6a,
	0xce, 0xb3, 0x08, 0x47, 0x04, 0x7d, 0x03, 0x65, 0xa5, 0x34, 0xb4, 0xbe, 0x36, 0xac, 0x1e, 0x74,
	0x46, 0xf7, 0xd7, 0x60, 0x74, 0x22, 0xa3, 0x13, 0xfd, 0xfa, 0xcf, 0x0f, 0x73, 0xbf, 0xfd, 0xfd,
	0xfb, 0x27, 0x9a, 0x99, 0x00, 0xe8, 0x6b, 0xd0, 0x65, 0xa7, 0x96, 0x87, 0x7d, 0x23, 0xdf, 0x2f,
	0x0c, 0xab, 0x07, 0xfb, 0x59, 0xfa, 0x9d, 0x48, 0x98, 0x14, 0x05, 0x6c, 0x56, 0x64, 0xf6, 0x3b,
	0xec, 0xa3, 0x03, 0xd8, 0x5b, 0x71, 0x5b, 0x72, 0x05, 0xc9, 0xb5, 0xb2, 0xdc, 0x31, 0xb7, 0x13,
	0xaa, 0xbc, 0xe2, 0xb6, 0x60, 0x3e, 0x85, 0x92, 0x9c, 0x9e, 0x51, 0x94, 0x7d, 0x3e, 0xa8, 0x74,
	0x22, 0x82, 0xa6, 0xca, 0x41, 0x87, 0x00, 0x6a, 0xed, 0x65, 0x8d, 0x92, 0xac, 0xf1, 0x60, 0x66,
	0x53, 0x99, 0x91, 0x94, 0xd1, 0x55, 0xbe, 0xa8, 0x74, 0x08, 0xa0, 0xde, 0xaa, 0x84, 0xcb, 0x8f,
	0xc3, 0x13, 0x99, 0x91, 0xc2, 0x2a, 0x5f, 0xc1, 0x95, 0x73, 0xe2, 0x3a, 0xd6, 0x82, 0x10, 0x63,
	0x4f, 0xa2, 0xdd, 0x2c, 0xfa, 0x3d, 0x71, 0x9d, 0xd7, 0x1e, 0x5f, 0xb3, 0xb4, 0xf6, 0x9e, 0x20,
	0xde, 0x10, 0x82, 0xbe, 0x05, 0x5d, 0xc2, 0xf6, 0x3a, 0x60, 0x46, 0x65, 0x47, 0x5a, 0xd6, 0x9b,
	0xac, 0x03, 0x86, 0x8e, 0xa0, 0xee, 0x13, 0xe6, 0x50, 0xb6, 0xb4, 0x02, 0x12, 0x13, 0xec, 0x1a,
	0xba, 0x74, 0xbc, 0x7c, 0xb0, 0x56, 0x2a, 0xeb, 0x3b, 0x16, 0x05, 0x57, 0x89, 0xe5, 0x59, 0x42,
	0x9a, 0x12, 0x44, 0x6f, 0x21, 0x1d, 0xb0, 0xf0, 0xda, 0xa1, 0x91, 0x01, 0x3b, 0x9b, 0x6a, 0x09,
	0xf8, 0x5a, 0x70, 0xe8, 0x3d, 0xec, 0xdf, 0x13, 0x59, 0x01, 0x09, 0xb9, 0x1b, 0x13, 0xa3, 0xba,
	0xb3, 0xb0, 0xb5, 0x2d, 0x34, 0x15, 0x8e, 0xce, 0xa0, 0xb3, 0xf1, 0xfa, 0x3e, 0xc1, 0xee, 0x46,
	0x5c, 0xdb, 0x59, 0xdc, 0x4e, 0xc5, 0x52, 0x90, 0x9a, 0x8f, 0xa1, 0xa1, 0x3a, 0x55, 0x3b, 0x22,
	0x22, 0xc4, 0x78, 0x26, 0x95, 0x2f, 0xb2, 0xca, 0x59, 0x14, 0x64, 0x8c, 0x75, 0x49, 0x4e, 0x53,
	0x10, 0xcd, 0xa0, 0x1d, 0x63, 0x97, 0x3a, 0x38, 0xe2, 0x81, 0x15, 0x07, 0x0b, 0xcb, 0x5f, 0xdb,
	0x17, 0xe4, 0xca, 0xa8, 0xef, 0x2a, 0x44, 0x1b, 0xfc, 0x7d, 0xb0, 0x38, 0x91, 0x30, 0x3a, 0x85,
	0x8e, 0xfa, 0xee, 0xb8, 0x1f, 0x51, 0x8f, 0x86, 0x11, 0x9d, 0x5b, 0x73, 0xb1, 0x21, 0x8c, 0xc6,
	0xe3, 0xda, 0x9f, 0x28, 0x8b, 0xbe, 0xfa, 0xe2, 0xde, 0xcc, 0xa5, 0xe0, 0xc7, 0x0d, 0x3f, 0x15,
	0x38, 0xfa, 0x01, 0x9a, 0x38, 0xc6, 0xd4, 0xb5, 0x16, 0xe2, 0xa2, 0x94, 0xcd, 0x5d, 0x95, 0x75,
	0x89, 0xbe, 0xc1, 0xd4, 0x55, 0xb2, 0x33, 0xf8, 0x60, 0x4b, 0x76, 0x49, 0x99, 0xc3, 0x2f, 0xad,
	0x30, 0xc2, 0x41, 0x64, 0x3c, 0xdf, 0xb9, 0xcd, 0x8d, 0xf3, 0x54, 0xf2, 0x33, 0x81, 0xa3, 0x8f,
	0xa0, 0xa1, 0xcc, 0xf3, 0x73, 0xec, 0xba, 0x84, 0x2d, 0x89, 0x81, 0xfa, 0xda, 0x50, 0x4f, 0x5a,
	0x98, 0xa6, 0xa3, 0xc7, 0xc5, 0x4a, 0xab, 0xd9, 0x1e, 0x1c, 0x02, 0xfc, 0xf7, 0xcd, 0xa0, 0x7d,
	0x10, 0x3f, 0x14, 0x8b, 0x3a, 0xf2, 0x7f, 0xa7, 0x9b, 0xa5, 0x15, 0xb7, 0x8f, 0x1c, 0xd4, 0x81,
	0x32, 0x96, 0x09, 0x46, 0xbe, 0xaf, 0x0d, 0x8b, 0x66, 0xf2, 0x34, 0x38, 0x82, 0xda, 0xf6, 0xc6,
	0x41, 0x1f, 0x43, 0xd3, 0x76, 0xf9, 0xfc, 0x22, 0xb4, 0x02, 0xe2, 0x61, 0xca, 0x28, 0x5b, 0x4a,
	0x51, 0xc1, 0x6c, 0xa8, 0x71, 0x33, 0x1d, 0x46, 0x75, 0xc8, 0x53, 0x47, 0xea, 0x74, 0x33, 0x4f,
	0x9d, 0xc1, 0x97, 0x50, 0xdd, 0x7a, 0xbf, 0xa8, 0x09, 0x05, 0xb1, 0x13, 0x54, 0x17, 0xe2, 0x16,
	0xb5, 0xa1, 0x14, 0x63, 0x77, 0x4d, 0x12, 0x46, 0x3d, 0x08, 0x6c, 0x6b, 0x61, 0xfe, 0x0f, 0x2b,
	0x26, 0xd8, 0xe4, 0xb3, 0xeb, 0xdb, 0x9e, 0x76, 0x73, 0xdb, 0xd3, 0xfe, 0xba, 0xed, 0x69, 0xbf,
	0xde, 0xf5, 0x72, 0x37, 0x77, 0xbd, 0xdc, 0x1f, 0x77, 0xbd, 0xdc, 0xcf, 0xad, 0xe4, 0xd0, 0xf8,
	0x45, 0x1d, 0x1b, 0xd1, 0x95, 0x4f, 0x42, 0xbb, 0x2c, 0x8f, 0x87, 0xcf, 0xff, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0x8f, 0xfb, 0xa4, 0x68, 0x20, 0x07, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AvailChallenge) > 0 {
		i -= len(m.AvailChallenge)
		copy(dAtA[i:], m.AvailChallenge)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.AvailChallenge)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if len(m.AvailFailWindowStart) > 0 {
		for iNdEx := len(m.AvailFailWindowStart) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AvailFailWindowStart[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x8a
		}
	}
	if len(m.AvailFailCount) > 0 {
		for iNdEx := len(m.AvailFailCount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AvailFailCount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
	}
	if len(m.MinerOptimisticCount) > 0 {
		for iNdEx := len(m.MinerOptimisticCount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MinerOptimisticCount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x7a
		}
	}
	if len(m.ValidatorVrfPubkey) > 0 {
		for iNdEx := len(m.ValidatorVrfPubkey) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorVrfPubkey[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x72
		}
	}
	if len(m.AuditCommittee) > 0 {
		for iNdEx := len(m.AuditCommittee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AuditCommittee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.PendingAppealResolve) > 0 {
		for iNdEx := len(m.PendingAppealResolve) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingAppealResolve[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.PendingAuditResolve) > 0 {
		for iNdEx := len(m.PendingAuditResolve) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingAuditResolve[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.PendingAudit) > 0 {
		for iNdEx := len(m.PendingAudit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingAudit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.PendingReveal) > 0 {
		for iNdEx := len(m.PendingReveal) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingReveal[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.HeldBurn) > 0 {
		for iNdEx := len(m.HeldBurn) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HeldBurn[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.HeldFee) > 0 {
		for iNdEx := len(m.HeldFee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HeldFee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.BeaconMap) > 0 {
		for iNdEx := len(m.BeaconMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BeaconMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.CommitMap) > 0 {
		for iNdEx := len(m.CommitMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CommitMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Pools != nil {
		{
			size, err := m.Pools.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.JobMap) > 0 {
		for iNdEx := len(m.JobMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.JobMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.MinerMap) > 0 {
		for iNdEx := len(m.MinerMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MinerMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *HeldAmount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HeldAmount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HeldAmount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.JobId) > 0 {
		i -= len(m.JobId)
		copy(dAtA[i:], m.JobId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.JobId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PendingEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if m.BlocksRemaining != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.BlocksRemaining))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StringEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StringEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StringEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Uint64Entry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Uint64Entry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Uint64Entry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Value != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Value))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.MinerMap) > 0 {
		for _, e := range m.MinerMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.JobMap) > 0 {
		for _, e := range m.JobMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.Pools != nil {
		l = m.Pools.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.CommitMap) > 0 {
		for _, e := range m.CommitMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BeaconMap) > 0 {
		for _, e := range m.BeaconMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HeldFee) > 0 {
		for _, e := range m.HeldFee {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HeldBurn) > 0 {
		for _, e := range m.HeldBurn {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingReveal) > 0 {
		for _, e := range m.PendingReveal {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingAudit) > 0 {
		for _, e := range m.PendingAudit {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingAuditResolve) > 0 {
		for _, e := range m.PendingAuditResolve {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingAppealResolve) > 0 {
		for _, e := range m.PendingAppealResolve {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.AuditCommittee) > 0 {
		for _, e := range m.AuditCommittee {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ValidatorVrfPubkey) > 0 {
		for _, e := range m.ValidatorVrfPubkey {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.MinerOptimisticCount) > 0 {
		for _, e := range m.MinerOptimisticCount {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.AvailFailCount) > 0 {
		for _, e := range m.AvailFailCount {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.AvailFailWindowStart) > 0 {
		for _, e := range m.AvailFailWindowStart {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	l = len(m.AvailChallenge)
	if l > 0 {
		n += 2 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *HeldAmount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.JobId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovGenesis(uint64(m.Amount))
	}
	return n
}

func (m *PendingEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlocksRemaining != 0 {
		n += 1 + sovGenesis(uint64(m.BlocksRemaining))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *StringEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *Uint64Entry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Value != 0 {
		n += 1 + sovGenesis(uint64(m.Value))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinerMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinerMap = append(m.MinerMap, Miner{})
			if err := m.MinerMap[len(m.MinerMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobMap = append(m.JobMap, Job{})
			if err := m.JobMap[len(m.JobMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pools", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pools == nil {
				m.Pools = &Pools{}
			}
			if err := m.Pools.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitMap = append(m.CommitMap, Commit{})
			if err := m.CommitMap[len(m.CommitMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BeaconMap = append(m.BeaconMap, Beacon{})
			if err := m.BeaconMap[len(m.BeaconMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeldFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HeldFee = append(m.HeldFee, HeldAmount{})
			if err := m.HeldFee[len(m.HeldFee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeldBurn", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HeldBurn = append(m.HeldBurn, HeldAmount{})
			if err := m.HeldBurn[len(m.HeldBurn)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingReveal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingReveal = append(m.PendingReveal, PendingEntry{})
			if err := m.PendingReveal[len(m.PendingReveal)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingAudit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingAudit = append(m.PendingAudit, PendingEntry{})
			if err := m.PendingAudit[len(m.PendingAudit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingAuditResolve", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingAuditResolve = append(m.PendingAuditResolve, PendingEntry{})
			if err := m.PendingAuditResolve[len(m.PendingAuditResolve)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingAppealResolve", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingAppealResolve = append(m.PendingAppealResolve, PendingEntry{})
			if err := m.PendingAppealResolve[len(m.PendingAppealResolve)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditCommittee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditCommittee = append(m.AuditCommittee, StringEntry{})
			if err := m.AuditCommittee[len(m.AuditCommittee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorVrfPubkey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorVrfPubkey = append(m.ValidatorVrfPubkey, StringEntry{})
			if err := m.ValidatorVrfPubkey[len(m.ValidatorVrfPubkey)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinerOptimisticCount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinerOptimisticCount = append(m.MinerOptimisticCount, Uint64Entry{})
			if err := m.MinerOptimisticCount[len(m.MinerOptimisticCount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailFailCount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvailFailCount = append(m.AvailFailCount, Uint64Entry{})
			if err := m.AvailFailCount[len(m.AvailFailCount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailFailWindowStart", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvailFailWindowStart = append(m.AvailFailWindowStart, Uint64Entry{})
			if err := m.AvailFailWindowStart[len(m.AvailFailWindowStart)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailChallenge", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvailChallenge = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HeldAmount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HeldAmount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HeldAmount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PendingEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksRemaining", wireType)
			}
			m.BlocksRemaining = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksRemaining |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StringEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StringEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StringEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Uint64Entry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Uint64Entry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Uint64Entry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			m.Value = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Value |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
