// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dendra/jobs/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the jobs module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params    Params   `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	MinerMap  []Miner  `protobuf:"bytes,2,rep,name=miner_map,json=minerMap,proto3" json:"miner_map"`
	JobMap    []Job    `protobuf:"bytes,3,rep,name=job_map,json=jobMap,proto3" json:"job_map"`
	Pools     *Pools   `protobuf:"bytes,4,opt,name=pools,proto3" json:"pools,omitempty"`
	CommitMap []Commit `protobuf:"bytes,5,rep,name=commit_map,json=commitMap,proto3" json:"commit_map"`
	BeaconMap []Beacon `protobuf:"bytes,6,rep,name=beacon_map,json=beaconMap,proto3" json:"beacon_map"`
	// VALUE. Fee and burn HELD per job. The coins stay in the module account either way, but without
	// these two tables nothing records who they belong to or when to release them: orphaned funds.
	HeldFee  []HeldAmount `protobuf:"bytes,7,rep,name=held_fee,json=heldFee,proto3" json:"held_fee"`
	HeldBurn []HeldAmount `protobuf:"bytes,8,rep,name=held_burn,json=heldBurn,proto3" json:"held_burn"`
	// DEADLINES. Each entry is an appointment the end blocker must keep. Losing one does not lose
	// coins directly, which is worse: the affected jobs never resolve, so their escrow and their held
	// fee stay locked and no error is ever raised.
	PendingReveal        []PendingEntry `protobuf:"bytes,9,rep,name=pending_reveal,json=pendingReveal,proto3" json:"pending_reveal"`
	PendingAudit         []PendingEntry `protobuf:"bytes,10,rep,name=pending_audit,json=pendingAudit,proto3" json:"pending_audit"`
	PendingAuditResolve  []PendingEntry `protobuf:"bytes,11,rep,name=pending_audit_resolve,json=pendingAuditResolve,proto3" json:"pending_audit_resolve"`
	PendingAppealResolve []PendingEntry `protobuf:"bytes,12,rep,name=pending_appeal_resolve,json=pendingAppealResolve,proto3" json:"pending_appeal_resolve"`
	// AUTHORIZATION. The anchored audit committee (ADR-032, ADR-033): who is entitled to vote. Absent,
	// the tally fails closed — safe, but every dispute in flight becomes inert.
	AuditCommittee []StringEntry `protobuf:"bytes,13,rep,name=audit_committee,json=auditCommittee,proto3" json:"audit_committee"`
	// Validator VRF keys. Without them the seed has no contributors, so grinding resistance is
	// INACTIVE until every validator re-anchors its key. The logs show it; the state does not.
	ValidatorVrfPubkey []StringEntry `protobuf:"bytes,14,rep,name=validator_vrf_pubkey,json=validatorVrfPubkey,proto3" json:"validator_vrf_pubkey"`
	// ANTI-ABUSE. Sybil probation counters. Reset to zero, an already-known miner restarts with a
	// fresh counter and buys back the full-audit period it had already served.
	MinerOptimisticCount []Uint64Entry `protobuf:"bytes,15,rep,name=miner_optimistic_count,json=minerOptimisticCount,proto3" json:"miner_optimistic_count"`
	// Sliding window of availability failures. Losing it erases the history that arms the slash.
	AvailFailCount       []Uint64Entry `protobuf:"bytes,16,rep,name=avail_fail_count,json=availFailCount,proto3" json:"avail_fail_count"`
	AvailFailWindowStart []Uint64Entry `protobuf:"bytes,17,rep,name=avail_fail_window_start,json=availFailWindowStart,proto3" json:"avail_fail_window_start"`
	// Current availability challenge. Proven presences are per-epoch and are not transported: see the
	// reserved field below.
	AvailChallenge string `protobuf:"bytes,18,opt,name=avail_challenge,json=availChallenge,proto3" json:"avail_challenge,omitempty"`
	// Jobs SELECTED by the audit lottery and waiting to be opened (ADR-034). Losing the marker on
	// migration would replay the lottery on the retry, which reopens the evasion it exists to close:
	// a miner that gets a second draw can have an audit cancelled by chance.
	AuditSelected []string `protobuf:"bytes,20,rep,name=audit_selected,json=auditSelected,proto3" json:"audit_selected,omitempty"`
	// Held-fee releases that are DUE after a failed transfer, retried once per epoch by the end
	// blocker. Losing the queue would make "a held fee stays claimable" false again after a
	// migration: held_fee itself travels in field 7, but nothing would retry it.
	PendingHeldRelease []string `protobuf:"bytes,21,rep,name=pending_held_release,json=pendingHeldRelease,proto3" json:"pending_held_release,omitempty"`
	// MONOTONIC count of audits opened — the INDEPENDENT side of the partition check (ADR-034).
	// Losing it on migration would break the sum permanently: the classes are counted from the
	// transported job states while this counter would restart at zero.
	AuditsOpened uint64 `protobuf:"varint,22,opt,name=audits_opened,json=auditsOpened,proto3" json:"audits_opened,omitempty"`
	// DATE of each held fee, transported as an AGE in elapsed blocks. Same relative rule as
	// PendingEntry: an absolute height designates nothing after a genesis, so the import re-anchors
	// `since = max(initial_height - value, 0)`. The clamp always keeps the debt OLD, never the
	// reverse — the oldest-held-fee alarm must survive a migration rather than reset to zero.
	HeldSinceElapsed []Uint64Entry `protobuf:"bytes,23,rep,name=held_since_elapsed,json=heldSinceElapsed,proto3" json:"held_since_elapsed"`
	// ANCHORING DATE of each seated committee, transported as an AGE under the same relative rule and
	// the same keep-it-old clamp as held_since_elapsed. A juror's seat lock must survive the
	// migration without rejuvenating, or the oldest-lock age would fall silent exactly when it
	// matters. The committee itself travels in audit_committee; its date travels here.
	CommitteeSinceElapsed []Uint64Entry `protobuf:"bytes,24,rep,name=committee_since_elapsed,json=committeeSinceElapsed,proto3" json:"committee_since_elapsed"`
	// EXPIRY OF AN UNSERVED JOB. Travels like the other deadlines, as an age re-anchored on import: an
	// absolute height means nothing after a genesis. Losing these entries does not lose coins directly,
	// which is worse -- the client's escrow of every job whose miner never answered would stay locked
	// for ever, with nothing to raise.
	PendingJobExpiry []PendingEntry `protobuf:"bytes,25,rep,name=pending_job_expiry,json=pendingJobExpiry,proto3" json:"pending_job_expiry"`
	// work_committee — the ANCHORED work committee of each job (ADR-045, entry 12), ordered member ids
	// joined by ',', element 0 being the primary. It travels for the same reason the audit committee
	// does: a committee that did not survive the export would be RE-DERIVED on import, hence from the
	// stake of that moment -- which is the defect the anchoring exists to close, back on the first
	// restart. Distinct from audit_committee on purpose: three consumers read every audit_committee
	// entry as a JURY SEAT.
	WorkCommittee []StringEntry `protobuf:"bytes,26,rep,name=work_committee,json=workCommittee,proto3" json:"work_committee"`
	// ADR-048 item 4 — THE PROTOCOL CUT OF EACH JOB, RETAINED UNTIL FINALITY. At settlement the three
	// shares stay in the module, per job, exactly like held_fee and held_burn: paid out at finality (the
	// validators' share to fee_collector, the team's to team_address, the treasury's into Pools), returned
	// to the client on a refund. They are COINS the module holds, so they travel: an export that dropped
	// them would leave the coins in the module account with no key that accounts for them.
	HeldValidatorShare []HeldAmount `protobuf:"bytes,27,rep,name=held_validator_share,json=heldValidatorShare,proto3" json:"held_validator_share"`
	HeldTeamShare      []HeldAmount `protobuf:"bytes,28,rep,name=held_team_share,json=heldTeamShare,proto3" json:"held_team_share"`
	HeldTreasuryShare  []HeldAmount `protobuf:"bytes,29,rep,name=held_treasury_share,json=heldTreasuryShare,proto3" json:"held_treasury_share"`
	// ADR-048 item 3 — the subsidy right of a job, credited to the miner's Demand at finality and not at
	// settlement. Not coins, but a right: dropping it on export would lose a miner's subsidy for work
	// already done, so it travels with the job it belongs to.
	HeldDemand []HeldAmount `protobuf:"bytes,30,rep,name=held_demand,json=heldDemand,proto3" json:"held_demand"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7af7667158ffbf, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetMinerMap() []Miner {
	if m != nil {
		return m.MinerMap
	}
	return nil
}

func (m *GenesisState) GetJobMap() []Job {
	if m != nil {
		return m.JobMap
	}
	return nil
}

func (m *GenesisState) GetPools() *Pools {
	if m != nil {
		return m.Pools
	}
	return nil
}

func (m *GenesisState) GetCommitMap() []Commit {
	if m != nil {
		return m.CommitMap
	}
	return nil
}

func (m *GenesisState) GetBeaconMap() []Beacon {
	if m != nil {
		return m.BeaconMap
	}
	return nil
}

func (m *GenesisState) GetHeldFee() []HeldAmount {
	if m != nil {
		return m.HeldFee
	}
	return nil
}

func (m *GenesisState) GetHeldBurn() []HeldAmount {
	if m != nil {
		return m.HeldBurn
	}
	return nil
}

func (m *GenesisState) GetPendingReveal() []PendingEntry {
	if m != nil {
		return m.PendingReveal
	}
	return nil
}

func (m *GenesisState) GetPendingAudit() []PendingEntry {
	if m != nil {
		return m.PendingAudit
	}
	return nil
}

func (m *GenesisState) GetPendingAuditResolve() []PendingEntry {
	if m != nil {
		return m.PendingAuditResolve
	}
	return nil
}

func (m *GenesisState) GetPendingAppealResolve() []PendingEntry {
	if m != nil {
		return m.PendingAppealResolve
	}
	return nil
}

func (m *GenesisState) GetAuditCommittee() []StringEntry {
	if m != nil {
		return m.AuditCommittee
	}
	return nil
}

func (m *GenesisState) GetValidatorVrfPubkey() []StringEntry {
	if m != nil {
		return m.ValidatorVrfPubkey
	}
	return nil
}

func (m *GenesisState) GetMinerOptimisticCount() []Uint64Entry {
	if m != nil {
		return m.MinerOptimisticCount
	}
	return nil
}

func (m *GenesisState) GetAvailFailCount() []Uint64Entry {
	if m != nil {
		return m.AvailFailCount
	}
	return nil
}

func (m *GenesisState) GetAvailFailWindowStart() []Uint64Entry {
	if m != nil {
		return m.AvailFailWindowStart
	}
	return nil
}

func (m *GenesisState) GetAvailChallenge() string {
	if m != nil {
		return m.AvailChallenge
	}
	return ""
}

func (m *GenesisState) GetAuditSelected() []string {
	if m != nil {
		return m.AuditSelected
	}
	return nil
}

func (m *GenesisState) GetPendingHeldRelease() []string {
	if m != nil {
		return m.PendingHeldRelease
	}
	return nil
}

func (m *GenesisState) GetAuditsOpened() uint64 {
	if m != nil {
		return m.AuditsOpened
	}
	return 0
}

func (m *GenesisState) GetHeldSinceElapsed() []Uint64Entry {
	if m != nil {
		return m.HeldSinceElapsed
	}
	return nil
}

func (m *GenesisState) GetCommitteeSinceElapsed() []Uint64Entry {
	if m != nil {
		return m.CommitteeSinceElapsed
	}
	return nil
}

func (m *GenesisState) GetPendingJobExpiry() []PendingEntry {
	if m != nil {
		return m.PendingJobExpiry
	}
	return nil
}

func (m *GenesisState) GetWorkCommittee() []StringEntry {
	if m != nil {
		return m.WorkCommittee
	}
	return nil
}

func (m *GenesisState) GetHeldValidatorShare() []HeldAmount {
	if m != nil {
		return m.HeldValidatorShare
	}
	return nil
}

func (m *GenesisState) GetHeldTeamShare() []HeldAmount {
	if m != nil {
		return m.HeldTeamShare
	}
	return nil
}

func (m *GenesisState) GetHeldTreasuryShare() []HeldAmount {
	if m != nil {
		return m.HeldTreasuryShare
	}
	return nil
}

func (m *GenesisState) GetHeldDemand() []HeldAmount {
	if m != nil {
		return m.HeldDemand
	}
	return nil
}

// HeldAmount is an amount withheld by the module on behalf of one job.
type HeldAmount struct {
	JobId  string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Amount uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *HeldAmount) Reset()         { *m = HeldAmount{} }
func (m *HeldAmount) String() string { return proto.CompactTextString(m) }
func (*HeldAmount) ProtoMessage()    {}
func (*HeldAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7af7667158ffbf, []int{1}
}
func (m *HeldAmount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HeldAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HeldAmount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HeldAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeldAmount.Merge(m, src)
}
func (m *HeldAmount) XXX_Size() int {
	return m.Size()
}
func (m *HeldAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_HeldAmount.DiscardUnknown(m)
}

var xxx_messageInfo_HeldAmount proto.InternalMessageInfo

func (m *HeldAmount) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *HeldAmount) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// PendingEntry is one appointment from a key set indexed by (height, identifier) pairs.
//
// `blocks_remaining` is RELATIVE, not an absolute height. Height-indexed collections are not
// transported at all because heights restart at genesis, and the same reasoning applies here: a
// deadline exported as an absolute height would fire thousands of blocks late on a chain restarted
// at 1, and would NEVER fire if the restart height is already past it, because the end blocker
// matches the exact height. What travels is therefore the TIME LEFT TO WAIT, which the import
// re-anchors on the height the chain resumes from.
type PendingEntry struct {
	BlocksRemaining int64  `protobuf:"varint,1,opt,name=blocks_remaining,json=blocksRemaining,proto3" json:"blocks_remaining,omitempty"`
	Id              string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *PendingEntry) Reset()         { *m = PendingEntry{} }
func (m *PendingEntry) String() string { return proto.CompactTextString(m) }
func (*PendingEntry) ProtoMessage()    {}
func (*PendingEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7af7667158ffbf, []int{2}
}
func (m *PendingEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingEntry.Merge(m, src)
}
func (m *PendingEntry) XXX_Size() int {
	return m.Size()
}
func (m *PendingEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PendingEntry proto.InternalMessageInfo

func (m *PendingEntry) GetBlocksRemaining() int64 {
	if m != nil {
		return m.BlocksRemaining
	}
	return 0
}

func (m *PendingEntry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// StringEntry is one entry of a string-keyed, string-valued map.
type StringEntry struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *StringEntry) Reset()         { *m = StringEntry{} }
func (m *StringEntry) String() string { return proto.CompactTextString(m) }
func (*StringEntry) ProtoMessage()    {}
func (*StringEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7af7667158ffbf, []int{3}
}
func (m *StringEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StringEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StringEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StringEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringEntry.Merge(m, src)
}
func (m *StringEntry) XXX_Size() int {
	return m.Size()
}
func (m *StringEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_StringEntry.DiscardUnknown(m)
}

var xxx_messageInfo_StringEntry proto.InternalMessageInfo

func (m *StringEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StringEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Uint64Entry is one entry of a string-keyed, uint64-valued map.
type Uint64Entry struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value uint64 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Uint64Entry) Reset()         { *m = Uint64Entry{} }
func (m *Uint64Entry) String() string { return proto.CompactTextString(m) }
func (*Uint64Entry) ProtoMessage()    {}
func (*Uint64Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec7af7667158ffbf, []int{4}
}
func (m *Uint64Entry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Uint64Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Uint64Entry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Uint64Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uint64Entry.Merge(m, src)
}
func (m *Uint64Entry) XXX_Size() int {
	return m.Size()
}
func (m *Uint64Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Uint64Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Uint64Entry proto.InternalMessageInfo

func (m *Uint64Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Uint64Entry) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "dendra.jobs.v1.GenesisState")
	proto.RegisterType((*HeldAmount)(nil), "dendra.jobs.v1.HeldAmount")
	proto.RegisterType((*PendingEntry)(nil), "dendra.jobs.v1.PendingEntry")
	proto.RegisterType((*StringEntry)(nil), "dendra.jobs.v1.StringEntry")
	proto.RegisterType((*Uint64Entry)(nil), "dendra.jobs.v1.Uint64Entry")
}

func init() { proto.RegisterFile("dendra/jobs/v1/genesis.proto", fileDescriptor_ec7af7667158ffbf) }

var fileDescriptor_ec7af7667158ffbf = []byte{
	// 1023 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x96, 0xcd, 0x4e, 0xe3, 0x56,
	0x14, 0x80, 0x09, 0x7f, 0x43, 0x0e, 0x90, 0x84, 0x4b, 0x80, 0x5b, 0xa0, 0x29, 0xa2, 0xaa, 0x4a,
	0x5b, 0x35, 0xe9, 0xd0, 0x1f, 0xb5, 0x45, 0x5d, 0x00, 0xc3, 0x0c, 0x50, 0x4d, 0x41, 0xce, 0x94,
	0x99, 0x76, 0x63, 0x5d, 0xdb, 0x87, 0x70, 0xc1, 0xf6, 0xb5, 0x6c, 0x27, 0x0c, 0x6f, 0xd1, 0xc7,
	0xe8, 0xb2, 0x8f, 0x31, 0xcb, 0x59, 0x76, 0x55, 0x55, 0xb0, 0xa8, 0xfa, 0x16, 0xd5, 0x3d, 0xd7,
	0x0e, 0x21, 0x0c, 0xaa, 0x37, 0x96, 0x7d, 0xce, 0xf9, 0xbe, 0xfb, 0x6f, 0x1b, 0x56, 0x3d, 0x0c,
	0xbd, 0x58, 0xb4, 0xce, 0x95, 0x93, 0xb4, 0x7a, 0x8f, 0x5b, 0x1d, 0x0c, 0x31, 0x91, 0x49, 0x33,
	0x8a, 0x55, 0xaa, 0x58, 0xc5, 0x64, 0x9b, 0x3a, 0xdb, 0xec, 0x3d, 0x5e, 0x9e, 0x13, 0x81, 0x0c,
	0x55, 0x8b, 0xae, 0xa6, 0x64, 0x79, 0x65, 0x48, 0xe0, 0xa0, 0x70, 0x55, 0xf8, 0x40, 0xd2, 0x55,
	0x41, 0x20, 0xd3, 0x2c, 0xc9, 0x87, 0x92, 0xe7, 0xca, 0xc9, 0x32, 0xcb, 0x43, 0x99, 0x40, 0x86,
	0x18, 0x3f, 0xa0, 0x8c, 0x44, 0x2c, 0x82, 0xe4, 0x01, 0x30, 0x52, 0xca, 0xcf, 0x73, 0xf5, 0x8e,
	0xea, 0x28, 0xba, 0x6d, 0xe9, 0x3b, 0x13, 0x5d, 0xff, 0xb7, 0x0a, 0x33, 0xcf, 0xcc, 0x98, 0xdb,
	0xa9, 0x48, 0x91, 0x7d, 0x07, 0x93, 0x46, 0xc9, 0x4b, 0x6b, 0xa5, 0x8d, 0xe9, 0xcd, 0xc5, 0xe6,
	0xdd, 0x39, 0x68, 0x1e, 0x53, 0x76, 0xa7, 0xfc, 0xe6, 0xaf, 0x0f, 0x46, 0x7e, 0xff, 0xe7, 0x8f,
	0x4f, 0x4b, 0x56, 0x06, 0xb0, 0x6f, 0xa1, 0x4c, 0x3d, 0xb5, 0x03, 0x11, 0xf1, 0xd1, 0xb5, 0xb1,
	0x8d, 0xe9, 0xcd, 0x85, 0x61, 0xfa, 0xb9, 0x2e, 0xd8, 0x19, 0xd7, 0xb0, 0x35, 0x45, 0xd5, 0xcf,
	0x45, 0xc4, 0x36, 0xe1, 0xd1, 0xb9, 0x72, 0x88, 0x1b, 0x23, 0x6e, 0x7e, 0x98, 0x3b, 0x54, 0x4e,
	0x46, 0x4d, 0x9e, 0x2b, 0x47, 0x33, 0x9f, 0xc1, 0x04, 0x0d, 0x8f, 0x8f, 0x53, 0x3f, 0xef, 0xb5,
	0x74, 0xac, 0x93, 0x96, 0xa9, 0x61, 0x5b, 0x00, 0x66, 0xee, 0xa9, 0x8d, 0x09, 0x6a, 0xe3, 0xde,
	0xc8, 0x76, 0xa9, 0x22, 0x6b, 0xa6, 0x6c, 0xea, 0x75, 0x4b, 0x5b, 0x00, 0x66, 0x55, 0x09, 0x9e,
	0x7c, 0x37, 0xbc, 0x43, 0x15, 0x39, 0x6c, 0xea, 0x0d, 0x3c, 0x75, 0x86, 0xbe, 0x67, 0x9f, 0x22,
	0xf2, 0x47, 0x84, 0x2e, 0x0f, 0xa3, 0xfb, 0xe8, 0x7b, 0xdb, 0x81, 0xea, 0x86, 0x79, 0xdb, 0x8f,
	0x34, 0xf1, 0x14, 0x91, 0xfd, 0x00, 0x65, 0x82, 0x9d, 0x6e, 0x1c, 0xf2, 0xa9, 0x82, 0x34, 0xb5,
	0xb7, 0xd3, 0x8d, 0x43, 0x76, 0x00, 0x95, 0x08, 0x43, 0x4f, 0x86, 0x1d, 0x3b, 0xc6, 0x1e, 0x0a,
	0x9f, 0x97, 0xc9, 0xb1, 0x7a, 0x6f, 0xae, 0x4c, 0xd5, 0x5e, 0x98, 0xc6, 0x57, 0x99, 0x65, 0x36,
	0x23, 0x2d, 0x02, 0xd9, 0x33, 0xc8, 0x03, 0xb6, 0xe8, 0x7a, 0x32, 0xe5, 0x50, 0xd8, 0x34, 0x93,
	0x81, 0xdb, 0x9a, 0x63, 0x27, 0xb0, 0x70, 0x47, 0x64, 0xc7, 0x98, 0x28, 0xbf, 0x87, 0x7c, 0xba,
	0xb0, 0x70, 0x7e, 0x50, 0x68, 0x19, 0x9c, 0xbd, 0x82, 0xc5, 0xbe, 0x37, 0x8a, 0x50, 0xf8, 0x7d,
	0xf1, 0x4c, 0x61, 0x71, 0x3d, 0x17, 0x93, 0x20, 0x37, 0x1f, 0x42, 0xd5, 0xf4, 0xd4, 0xec, 0x88,
	0x14, 0x91, 0xcf, 0x92, 0x72, 0x65, 0x58, 0xd9, 0x4e, 0xe3, 0x21, 0x63, 0x85, 0xc8, 0xdd, 0x1c,
	0x64, 0x6d, 0xa8, 0xf7, 0x84, 0x2f, 0x3d, 0x91, 0xaa, 0xd8, 0xee, 0xc5, 0xa7, 0x76, 0xd4, 0x75,
	0x2e, 0xf0, 0x8a, 0x57, 0x8a, 0x0a, 0x59, 0x1f, 0x3f, 0x89, 0x4f, 0x8f, 0x09, 0x66, 0x2f, 0x61,
	0xd1, 0x9c, 0x3b, 0x15, 0xa5, 0x32, 0x90, 0x49, 0x2a, 0x5d, 0xdb, 0xd5, 0x1b, 0x82, 0x57, 0xdf,
	0xad, 0xfd, 0x59, 0x86, 0xe9, 0x37, 0x5f, 0xdd, 0x19, 0x39, 0x09, 0x8e, 0xfa, 0xfc, 0xae, 0xc6,
	0xd9, 0x8f, 0x50, 0x13, 0x3d, 0x21, 0x7d, 0xfb, 0x54, 0x5f, 0x8c, 0xb2, 0x56, 0x54, 0x59, 0x21,
	0xf4, 0xa9, 0x90, 0xbe, 0x91, 0xbd, 0x82, 0xa5, 0x01, 0xd9, 0xa5, 0x0c, 0x3d, 0x75, 0x69, 0x27,
	0xa9, 0x88, 0x53, 0x3e, 0x57, 0xb8, 0x9b, 0x7d, 0xe7, 0x4b, 0xe2, 0xdb, 0x1a, 0x67, 0x1f, 0x43,
	0xd5, 0x98, 0xdd, 0x33, 0xe1, 0xfb, 0x18, 0x76, 0x90, 0xb3, 0xb5, 0xd2, 0x46, 0x39, 0xeb, 0xc2,
	0x6e, 0x1e, 0x65, 0x1f, 0x81, 0x59, 0x0f, 0x3b, 0x41, 0x1f, 0xdd, 0x14, 0x3d, 0x5e, 0x5f, 0x1b,
	0xdb, 0x28, 0x5b, 0xb3, 0x14, 0x6d, 0x67, 0x41, 0xf6, 0x05, 0xe4, 0x1b, 0xc1, 0xa6, 0xd3, 0x17,
	0xa3, 0x8f, 0x22, 0x41, 0xbe, 0x40, 0xc5, 0x2c, 0xcb, 0xe9, 0x73, 0x67, 0x99, 0x0c, 0xfb, 0x10,
	0x8c, 0x22, 0xb1, 0x55, 0x84, 0x21, 0x7a, 0x7c, 0x71, 0xad, 0xb4, 0x31, 0x6e, 0xcd, 0x98, 0xe0,
	0x11, 0xc5, 0xd8, 0x11, 0x30, 0xd2, 0x25, 0x32, 0x74, 0xd1, 0x46, 0x5f, 0x44, 0x09, 0x7a, 0x7c,
	0xa9, 0xe8, 0xd8, 0x6b, 0x1a, 0x6e, 0x6b, 0x76, 0xcf, 0xa0, 0xec, 0x17, 0x58, 0xea, 0x6f, 0xc9,
	0x21, 0x2b, 0x2f, 0x6a, 0x5d, 0xe8, 0x1b, 0xee, 0xa8, 0x8f, 0x21, 0x1f, 0xa6, 0xad, 0x5f, 0xcc,
	0xf8, 0x3a, 0x92, 0xf1, 0x15, 0x7f, 0xaf, 0xf0, 0x49, 0xaa, 0x65, 0xf4, 0xa1, 0x72, 0xf6, 0x88,
	0x65, 0xfb, 0x50, 0xb9, 0x54, 0xf1, 0xc5, 0xc0, 0x21, 0x5a, 0x2e, 0xba, 0xe7, 0x67, 0x35, 0x78,
	0x7b, 0x86, 0x2c, 0xa8, 0xd3, 0x3c, 0xde, 0x1e, 0xa4, 0xe4, 0x4c, 0xc4, 0xc8, 0x57, 0x0a, 0xbe,
	0x1f, 0x69, 0x15, 0x4e, 0x72, 0xb8, 0xad, 0x59, 0xb6, 0x0f, 0x55, 0x72, 0xa6, 0x28, 0x82, 0x4c,
	0xb7, 0x5a, 0x50, 0x37, 0xab, 0xc1, 0x17, 0x28, 0x02, 0x63, 0x3a, 0x86, 0x79, 0x63, 0x8a, 0x51,
	0x24, 0xdd, 0xf8, 0x2a, 0xb3, 0xbd, 0x5f, 0xd0, 0x36, 0x47, 0xb6, 0x8c, 0x35, 0xc6, 0x6d, 0x98,
	0x26, 0xa3, 0x87, 0x81, 0x08, 0x3d, 0xde, 0x28, 0x68, 0x02, 0x0d, 0x3d, 0x21, 0xe6, 0x70, 0x7c,
	0x6a, 0xbe, 0x56, 0x5f, 0xdf, 0x02, 0xb8, 0xad, 0x62, 0x0b, 0xa0, 0xbf, 0xa4, 0xb6, 0xf4, 0xe8,
	0x43, 0x5f, 0xb6, 0x26, 0xce, 0x95, 0x73, 0xe0, 0xb1, 0x45, 0x98, 0x14, 0x54, 0xc0, 0x47, 0x69,
	0x0f, 0x67, 0x4f, 0xeb, 0x07, 0x30, 0x33, 0xb8, 0xce, 0xec, 0x13, 0xa8, 0x39, 0xbe, 0x72, 0x2f,
	0x12, 0x3b, 0xc6, 0x40, 0xc8, 0x50, 0x86, 0x1d, 0x12, 0x8d, 0x59, 0x55, 0x13, 0xb7, 0xf2, 0x30,
	0xab, 0xc0, 0xa8, 0xf4, 0x48, 0x57, 0xb6, 0x46, 0xa5, 0xb7, 0xfe, 0x35, 0x4c, 0x0f, 0x2c, 0x32,
	0xab, 0xc1, 0x98, 0x7e, 0x05, 0x9a, 0x5e, 0xe8, 0x5b, 0x56, 0x87, 0x89, 0x9e, 0xf0, 0xbb, 0x98,
	0x31, 0xe6, 0x41, 0x63, 0x03, 0xfb, 0xf7, 0xff, 0xb0, 0xf1, 0x0c, 0xdb, 0x79, 0xf1, 0xe6, 0xba,
	0x51, 0x7a, 0x7b, 0xdd, 0x28, 0xfd, 0x7d, 0xdd, 0x28, 0xfd, 0x76, 0xd3, 0x18, 0x79, 0x7b, 0xd3,
	0x18, 0xf9, 0xf3, 0xa6, 0x31, 0xf2, 0xeb, 0xf7, 0x1d, 0x99, 0x9e, 0x75, 0x9d, 0xa6, 0xab, 0x82,
	0xd6, 0x13, 0x9a, 0xcd, 0x9f, 0x30, 0xd5, 0x7b, 0xad, 0x65, 0xe6, 0xf6, 0xf3, 0x30, 0x7b, 0x74,
	0xcf, 0x84, 0x0c, 0x5b, 0xaf, 0xcd, 0x6f, 0x55, 0x7a, 0x15, 0x61, 0xe2, 0x4c, 0xd2, 0xef, 0xd3,
	0x97, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x74, 0x51, 0x88, 0x40, 0x0a, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HeldDemand) > 0 {
		for iNdEx := len(m.HeldDemand) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HeldDemand[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xf2
		}
	}
	if len(m.HeldTreasuryShare) > 0 {
		for iNdEx := len(m.HeldTreasuryShare) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HeldTreasuryShare[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xea
		}
	}
	if len(m.HeldTeamShare) > 0 {
		for iNdEx := len(m.HeldTeamShare) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HeldTeamShare[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xe2
		}
	}
	if len(m.HeldValidatorShare) > 0 {
		for iNdEx := len(m.HeldValidatorShare) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HeldValidatorShare[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xda
		}
	}
	if len(m.WorkCommittee) > 0 {
		for iNdEx := len(m.WorkCommittee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WorkCommittee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xd2
		}
	}
	if len(m.PendingJobExpiry) > 0 {
		for iNdEx := len(m.PendingJobExpiry) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingJobExpiry[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xca
		}
	}
	if len(m.CommitteeSinceElapsed) > 0 {
		for iNdEx := len(m.CommitteeSinceElapsed) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CommitteeSinceElapsed[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xc2
		}
	}
	if len(m.HeldSinceElapsed) > 0 {
		for iNdEx := len(m.HeldSinceElapsed) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HeldSinceElapsed[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xba
		}
	}
	if m.AuditsOpened != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.AuditsOpened))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if len(m.PendingHeldRelease) > 0 {
		for iNdEx := len(m.PendingHeldRelease) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PendingHeldRelease[iNdEx])
			copy(dAtA[i:], m.PendingHeldRelease[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.PendingHeldRelease[iNdEx])))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xaa
		}
	}
	if len(m.AuditSelected) > 0 {
		for iNdEx := len(m.AuditSelected) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AuditSelected[iNdEx])
			copy(dAtA[i:], m.AuditSelected[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.AuditSelected[iNdEx])))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xa2
		}
	}
	if len(m.AvailChallenge) > 0 {
		i -= len(m.AvailChallenge)
		copy(dAtA[i:], m.AvailChallenge)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.AvailChallenge)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if len(m.AvailFailWindowStart) > 0 {
		for iNdEx := len(m.AvailFailWindowStart) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AvailFailWindowStart[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x8a
		}
	}
	if len(m.AvailFailCount) > 0 {
		for iNdEx := len(m.AvailFailCount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AvailFailCount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
	}
	if len(m.MinerOptimisticCount) > 0 {
		for iNdEx := len(m.MinerOptimisticCount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MinerOptimisticCount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x7a
		}
	}
	if len(m.ValidatorVrfPubkey) > 0 {
		for iNdEx := len(m.ValidatorVrfPubkey) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorVrfPubkey[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x72
		}
	}
	if len(m.AuditCommittee) > 0 {
		for iNdEx := len(m.AuditCommittee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AuditCommittee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.PendingAppealResolve) > 0 {
		for iNdEx := len(m.PendingAppealResolve) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingAppealResolve[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.PendingAuditResolve) > 0 {
		for iNdEx := len(m.PendingAuditResolve) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingAuditResolve[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.PendingAudit) > 0 {
		for iNdEx := len(m.PendingAudit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingAudit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.PendingReveal) > 0 {
		for iNdEx := len(m.PendingReveal) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingReveal[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.HeldBurn) > 0 {
		for iNdEx := len(m.HeldBurn) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HeldBurn[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.HeldFee) > 0 {
		for iNdEx := len(m.HeldFee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HeldFee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.BeaconMap) > 0 {
		for iNdEx := len(m.BeaconMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BeaconMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.CommitMap) > 0 {
		for iNdEx := len(m.CommitMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CommitMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Pools != nil {
		{
			size, err := m.Pools.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.JobMap) > 0 {
		for iNdEx := len(m.JobMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.JobMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.MinerMap) > 0 {
		for iNdEx := len(m.MinerMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MinerMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *HeldAmount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HeldAmount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HeldAmount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.JobId) > 0 {
		i -= len(m.JobId)
		copy(dAtA[i:], m.JobId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.JobId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PendingEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if m.BlocksRemaining != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.BlocksRemaining))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StringEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StringEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StringEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Uint64Entry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Uint64Entry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Uint64Entry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Value != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Value))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.MinerMap) > 0 {
		for _, e := range m.MinerMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.JobMap) > 0 {
		for _, e := range m.JobMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.Pools != nil {
		l = m.Pools.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.CommitMap) > 0 {
		for _, e := range m.CommitMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BeaconMap) > 0 {
		for _, e := range m.BeaconMap {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HeldFee) > 0 {
		for _, e := range m.HeldFee {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HeldBurn) > 0 {
		for _, e := range m.HeldBurn {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingReveal) > 0 {
		for _, e := range m.PendingReveal {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingAudit) > 0 {
		for _, e := range m.PendingAudit {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingAuditResolve) > 0 {
		for _, e := range m.PendingAuditResolve {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingAppealResolve) > 0 {
		for _, e := range m.PendingAppealResolve {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.AuditCommittee) > 0 {
		for _, e := range m.AuditCommittee {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ValidatorVrfPubkey) > 0 {
		for _, e := range m.ValidatorVrfPubkey {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.MinerOptimisticCount) > 0 {
		for _, e := range m.MinerOptimisticCount {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.AvailFailCount) > 0 {
		for _, e := range m.AvailFailCount {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.AvailFailWindowStart) > 0 {
		for _, e := range m.AvailFailWindowStart {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	l = len(m.AvailChallenge)
	if l > 0 {
		n += 2 + l + sovGenesis(uint64(l))
	}
	if len(m.AuditSelected) > 0 {
		for _, s := range m.AuditSelected {
			l = len(s)
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingHeldRelease) > 0 {
		for _, s := range m.PendingHeldRelease {
			l = len(s)
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if m.AuditsOpened != 0 {
		n += 2 + sovGenesis(uint64(m.AuditsOpened))
	}
	if len(m.HeldSinceElapsed) > 0 {
		for _, e := range m.HeldSinceElapsed {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CommitteeSinceElapsed) > 0 {
		for _, e := range m.CommitteeSinceElapsed {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingJobExpiry) > 0 {
		for _, e := range m.PendingJobExpiry {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.WorkCommittee) > 0 {
		for _, e := range m.WorkCommittee {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HeldValidatorShare) > 0 {
		for _, e := range m.HeldValidatorShare {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HeldTeamShare) > 0 {
		for _, e := range m.HeldTeamShare {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HeldTreasuryShare) > 0 {
		for _, e := range m.HeldTreasuryShare {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.HeldDemand) > 0 {
		for _, e := range m.HeldDemand {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *HeldAmount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.JobId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovGenesis(uint64(m.Amount))
	}
	return n
}

func (m *PendingEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlocksRemaining != 0 {
		n += 1 + sovGenesis(uint64(m.BlocksRemaining))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *StringEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *Uint64Entry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Value != 0 {
		n += 1 + sovGenesis(uint64(m.Value))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinerMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinerMap = append(m.MinerMap, Miner{})
			if err := m.MinerMap[len(m.MinerMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobMap = append(m.JobMap, Job{})
			if err := m.JobMap[len(m.JobMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pools", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pools == nil {
				m.Pools = &Pools{}
			}
			if err := m.Pools.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitMap = append(m.CommitMap, Commit{})
			if err := m.CommitMap[len(m.CommitMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BeaconMap = append(m.BeaconMap, Beacon{})
			if err := m.BeaconMap[len(m.BeaconMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeldFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HeldFee = append(m.HeldFee, HeldAmount{})
			if err := m.HeldFee[len(m.HeldFee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeldBurn", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HeldBurn = append(m.HeldBurn, HeldAmount{})
			if err := m.HeldBurn[len(m.HeldBurn)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingReveal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingReveal = append(m.PendingReveal, PendingEntry{})
			if err := m.PendingReveal[len(m.PendingReveal)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingAudit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingAudit = append(m.PendingAudit, PendingEntry{})
			if err := m.PendingAudit[len(m.PendingAudit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingAuditResolve", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingAuditResolve = append(m.PendingAuditResolve, PendingEntry{})
			if err := m.PendingAuditResolve[len(m.PendingAuditResolve)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingAppealResolve", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingAppealResolve = append(m.PendingAppealResolve, PendingEntry{})
			if err := m.PendingAppealResolve[len(m.PendingAppealResolve)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditCommittee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditCommittee = append(m.AuditCommittee, StringEntry{})
			if err := m.AuditCommittee[len(m.AuditCommittee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorVrfPubkey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorVrfPubkey = append(m.ValidatorVrfPubkey, StringEntry{})
			if err := m.ValidatorVrfPubkey[len(m.ValidatorVrfPubkey)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinerOptimisticCount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinerOptimisticCount = append(m.MinerOptimisticCount, Uint64Entry{})
			if err := m.MinerOptimisticCount[len(m.MinerOptimisticCount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailFailCount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvailFailCount = append(m.AvailFailCount, Uint64Entry{})
			if err := m.AvailFailCount[len(m.AvailFailCount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailFailWindowStart", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvailFailWindowStart = append(m.AvailFailWindowStart, Uint64Entry{})
			if err := m.AvailFailWindowStart[len(m.AvailFailWindowStart)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailChallenge", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvailChallenge = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditSelected", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditSelected = append(m.AuditSelected, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingHeldRelease", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingHeldRelease = append(m.PendingHeldRelease, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditsOpened", wireType)
			}
			m.AuditsOpened = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuditsOpened |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeldSinceElapsed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HeldSinceElapsed = append(m.HeldSinceElapsed, Uint64Entry{})
			if err := m.HeldSinceElapsed[len(m.HeldSinceElapsed)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 24:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitteeSinceElapsed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitteeSinceElapsed = append(m.CommitteeSinceElapsed, Uint64Entry{})
			if err := m.CommitteeSinceElapsed[len(m.CommitteeSinceElapsed)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingJobExpiry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingJobExpiry = append(m.PendingJobExpiry, PendingEntry{})
			if err := m.PendingJobExpiry[len(m.PendingJobExpiry)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 26:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkCommittee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkCommittee = append(m.WorkCommittee, StringEntry{})
			if err := m.WorkCommittee[len(m.WorkCommittee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 27:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeldValidatorShare", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HeldValidatorShare = append(m.HeldValidatorShare, HeldAmount{})
			if err := m.HeldValidatorShare[len(m.HeldValidatorShare)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 28:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeldTeamShare", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HeldTeamShare = append(m.HeldTeamShare, HeldAmount{})
			if err := m.HeldTeamShare[len(m.HeldTeamShare)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 29:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeldTreasuryShare", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HeldTreasuryShare = append(m.HeldTreasuryShare, HeldAmount{})
			if err := m.HeldTreasuryShare[len(m.HeldTreasuryShare)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 30:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeldDemand", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HeldDemand = append(m.HeldDemand, HeldAmount{})
			if err := m.HeldDemand[len(m.HeldDemand)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HeldAmount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HeldAmount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HeldAmount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PendingEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksRemaining", wireType)
			}
			m.BlocksRemaining = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksRemaining |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StringEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StringEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StringEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Uint64Entry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Uint64Entry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Uint64Entry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			m.Value = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Value |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
