// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dendra/jobs/v1/job.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Job is one unit of paid inference: who asked for it, who serves it, what it pays, and the trace
// of how it was settled or contested.
type Job struct {
	JobId   string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Client  string `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	MinerId string `protobuf:"bytes,3,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	Fee     uint64 `protobuf:"varint,4,opt,name=fee,proto3" json:"fee,omitempty"`
	State   string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Creator string `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	// Dispute state (bonded re-adjudication). All three fields are OPTIONAL: they hold the zero value
	// (0 / "") for a job that was never disputed.
	Disputer      string `protobuf:"bytes,7,opt,name=disputer,proto3" json:"disputer,omitempty"`
	DisputeBond   uint64 `protobuf:"varint,8,opt,name=dispute_bond,json=disputeBond,proto3" json:"dispute_bond,omitempty"`
	DisputeHeight int64  `protobuf:"varint,9,opt,name=dispute_height,json=disputeHeight,proto3" json:"dispute_height,omitempty"`
	// Record of the slashes applied at settlement. It exists so the slashes can be REVERSED: when a
	// dispute is upheld, resolution re-credits exactly these stakes from the treasury. Without a
	// record of who lost how much, an unjust slash is irreversible even once it is proven unjust.
	SlashRecords []SlashRecord `protobuf:"bytes,10,rep,name=slash_records,json=slashRecords,proto3" json:"slash_records"`
	// Number of DISTINCT OPERATORS behind the votes counted when the audit resolved (0 for a job with
	// no resolved audit or no voter). A quorum reached by fifteen seats all held by one operator is a
	// quorum in form only; monitoring reads the minimum of this field over its window. Without it,
	// the measurement describes a procedure rather than a plurality (ADR-034).
	AuditDistinctVoters uint64 `protobuf:"varint,11,opt,name=audit_distinct_voters,json=auditDistinctVoters,proto3" json:"audit_distinct_voters,omitempty"`
	// Plurality is not counted in heads: "distinct >= 2" is satisfied when a single operator holds
	// nine votes out of ten. The property that matters is that NO operator held a MAJORITY of the
	// votes counted, i.e. audit_max_operator_votes / audit_voters < 50%. Both fields are counted in
	// the SAME loop as the tally itself, never in a second pass: two traversals of the same state
	// drift apart, and a plurality figure that disagrees with the tally it describes is worse than none.
	AuditVoters           uint64 `protobuf:"varint,12,opt,name=audit_voters,json=auditVoters,proto3" json:"audit_voters,omitempty"`
	AuditMaxOperatorVotes uint64 `protobuf:"varint,13,opt,name=audit_max_operator_votes,json=auditMaxOperatorVotes,proto3" json:"audit_max_operator_votes,omitempty"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353edfac1b4d5fe, []int{0}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Job.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return m.Size()
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *Job) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *Job) GetMinerId() string {
	if m != nil {
		return m.MinerId
	}
	return ""
}

func (m *Job) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Job) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Job) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Job) GetDisputer() string {
	if m != nil {
		return m.Disputer
	}
	return ""
}

func (m *Job) GetDisputeBond() uint64 {
	if m != nil {
		return m.DisputeBond
	}
	return 0
}

func (m *Job) GetDisputeHeight() int64 {
	if m != nil {
		return m.DisputeHeight
	}
	return 0
}

func (m *Job) GetSlashRecords() []SlashRecord {
	if m != nil {
		return m.SlashRecords
	}
	return nil
}

func (m *Job) GetAuditDistinctVoters() uint64 {
	if m != nil {
		return m.AuditDistinctVoters
	}
	return 0
}

func (m *Job) GetAuditVoters() uint64 {
	if m != nil {
		return m.AuditVoters
	}
	return 0
}

func (m *Job) GetAuditMaxOperatorVotes() uint64 {
	if m != nil {
		return m.AuditMaxOperatorVotes
	}
	return 0
}

// SlashRecord is one slash applied to one miner at job settlement: who lost stake and how much.
// It is the evidence that lets a successful dispute undo the slash.
type SlashRecord struct {
	MinerId string `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	Amount  uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *SlashRecord) Reset()         { *m = SlashRecord{} }
func (m *SlashRecord) String() string { return proto.CompactTextString(m) }
func (*SlashRecord) ProtoMessage()    {}
func (*SlashRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_1353edfac1b4d5fe, []int{1}
}
func (m *SlashRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SlashRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SlashRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SlashRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlashRecord.Merge(m, src)
}
func (m *SlashRecord) XXX_Size() int {
	return m.Size()
}
func (m *SlashRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_SlashRecord.DiscardUnknown(m)
}

var xxx_messageInfo_SlashRecord proto.InternalMessageInfo

func (m *SlashRecord) GetMinerId() string {
	if m != nil {
		return m.MinerId
	}
	return ""
}

func (m *SlashRecord) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*Job)(nil), "dendra.jobs.v1.Job")
	proto.RegisterType((*SlashRecord)(nil), "dendra.jobs.v1.SlashRecord")
}

func init() { proto.RegisterFile("dendra/jobs/v1/job.proto", fileDescriptor_1353edfac1b4d5fe) }

var fileDescriptor_1353edfac1b4d5fe = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x52, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x6f, 0x48, 0x9b, 0x76, 0x6e, 0x3b, 0x21, 0xb3, 0x4d, 0x66, 0x48, 0xa1, 0x4c, 0x42, 0xea,
	0x85, 0x44, 0x1b, 0x07, 0x24, 0x4e, 0xa8, 0x9a, 0x10, 0x43, 0x02, 0xa4, 0x80, 0x38, 0x70, 0x89,
	0x92, 0xd8, 0x34, 0x2e, 0x6b, 0x5e, 0x65, 0xbb, 0xa5, 0x7c, 0x0b, 0x3e, 0xd6, 0x6e, 0xf4, 0xc8,
	0x09, 0xa1, 0xf6, 0x8b, 0x20, 0x3f, 0x1b, 0x58, 0x4f, 0x7e, 0xbf, 0x3f, 0xcf, 0x7f, 0x7e, 0xcf,
	0x84, 0x71, 0xd1, 0x70, 0x55, 0xa4, 0x33, 0x28, 0x75, 0xba, 0x3a, 0xb7, 0x6b, 0xb2, 0x50, 0x60,
	0x80, 0x1e, 0x3a, 0x25, 0xb1, 0x4a, 0xb2, 0x3a, 0x3f, 0x3d, 0x9a, 0xc2, 0x14, 0x50, 0x4a, 0x6d,
	0xe5, 0x5c, 0x67, 0x3f, 0x42, 0x12, 0xbe, 0x86, 0x92, 0x1e, 0x93, 0x68, 0x06, 0x65, 0x2e, 0x39,
	0x0b, 0x46, 0xc1, 0xf8, 0x20, 0xeb, 0xcc, 0xa0, 0xbc, 0xe2, 0xf4, 0x84, 0x44, 0xd5, 0xb5, 0x14,
	0x8d, 0x61, 0x77, 0x90, 0xf6, 0x88, 0xde, 0x27, 0xbd, 0xb9, 0x6c, 0x84, 0xb2, 0x0d, 0x21, 0x2a,
	0x5d, 0xc4, 0x57, 0x9c, 0xde, 0x25, 0xe1, 0x67, 0x21, 0x58, 0x7b, 0x14, 0x8c, 0xdb, 0x99, 0x2d,
	0xe9, 0x11, 0xe9, 0x68, 0x53, 0x18, 0xc1, 0x3a, 0x6e, 0x6b, 0x04, 0x94, 0x91, 0x6e, 0xa5, 0x44,
	0x61, 0x40, 0xb1, 0xc8, 0xed, 0xe0, 0x21, 0x3d, 0x25, 0x3d, 0x2e, 0xf5, 0x62, 0x69, 0x84, 0x62,
	0x5d, 0x94, 0xfe, 0x61, 0xfa, 0x88, 0x0c, 0x7c, 0x9d, 0x97, 0xd0, 0x70, 0xd6, 0xc3, 0x63, 0xfa,
	0x9e, 0x9b, 0x40, 0xc3, 0xe9, 0x63, 0x72, 0xf8, 0xd7, 0x52, 0x0b, 0x39, 0xad, 0x0d, 0x3b, 0x18,
	0x05, 0xe3, 0x30, 0x1b, 0x7a, 0xf6, 0x15, 0x92, 0xf4, 0x25, 0x19, 0xea, 0xeb, 0x42, 0xd7, 0xb9,
	0x12, 0x15, 0x28, 0xae, 0x19, 0x19, 0x85, 0xe3, 0xfe, 0xc5, 0x83, 0x64, 0x3f, 0xb7, 0xe4, 0xbd,
	0x35, 0x65, 0xe8, 0x99, 0xb4, 0x6f, 0x7e, 0x3d, 0x6c, 0x65, 0x03, 0xfd, 0x9f, 0xd2, 0xf4, 0x82,
	0x1c, 0x17, 0x4b, 0x2e, 0x4d, 0xce, 0xa5, 0x36, 0xb2, 0xa9, 0x4c, 0xbe, 0x02, 0x23, 0x94, 0x66,
	0x7d, 0xbc, 0xda, 0x3d, 0x14, 0x2f, 0xbd, 0xf6, 0x11, 0x25, 0xfb, 0x0a, 0xd7, 0xe3, 0xad, 0x03,
	0xf7, 0x0a, 0xe4, 0xbc, 0xe5, 0x19, 0x61, 0xce, 0x32, 0x2f, 0xd6, 0x39, 0x2c, 0x84, 0xb2, 0xd1,
	0xa0, 0x5f, 0xb3, 0x21, 0xda, 0xdd, 0xb1, 0x6f, 0x8a, 0xf5, 0x3b, 0xaf, 0xda, 0x4e, 0x7d, 0xf6,
	0x82, 0xf4, 0x6f, 0x5d, 0x79, 0x6f, 0x52, 0xc1, 0xfe, 0xa4, 0x4e, 0x48, 0x54, 0xcc, 0x61, 0xe9,
	0x87, 0xdb, 0xce, 0x3c, 0x9a, 0x7c, 0xb8, 0xd9, 0xc6, 0xc1, 0x66, 0x1b, 0x07, 0xbf, 0xb7, 0x71,
	0xf0, 0x7d, 0x17, 0xb7, 0x36, 0xbb, 0xb8, 0xf5, 0x73, 0x17, 0xb7, 0x3e, 0x3d, 0x9f, 0x4a, 0x53,
	0x2f, 0xcb, 0xa4, 0x82, 0x79, 0x7a, 0x89, 0x31, 0xbd, 0x15, 0xe6, 0x2b, 0xa8, 0x2f, 0xa9, 0x0b,
	0xed, 0x49, 0xe3, 0x61, 0x55, 0x17, 0xb2, 0x49, 0xd7, 0xee, 0x5b, 0x9a, 0x6f, 0x0b, 0xa1, 0xcb,
	0x08, 0x3f, 0xdc, 0xd3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x76, 0x77, 0x92, 0xb2, 0x02,
	0x00, 0x00,
}

func (m *Job) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Job) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Job) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AuditMaxOperatorVotes != 0 {
		i = encodeVarintJob(dAtA, i, uint64(m.AuditMaxOperatorVotes))
		i--
		dAtA[i] = 0x68
	}
	if m.AuditVoters != 0 {
		i = encodeVarintJob(dAtA, i, uint64(m.AuditVoters))
		i--
		dAtA[i] = 0x60
	}
	if m.AuditDistinctVoters != 0 {
		i = encodeVarintJob(dAtA, i, uint64(m.AuditDistinctVoters))
		i--
		dAtA[i] = 0x58
	}
	if len(m.SlashRecords) > 0 {
		for iNdEx := len(m.SlashRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SlashRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintJob(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.DisputeHeight != 0 {
		i = encodeVarintJob(dAtA, i, uint64(m.DisputeHeight))
		i--
		dAtA[i] = 0x48
	}
	if m.DisputeBond != 0 {
		i = encodeVarintJob(dAtA, i, uint64(m.DisputeBond))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Disputer) > 0 {
		i -= len(m.Disputer)
		copy(dAtA[i:], m.Disputer)
		i = encodeVarintJob(dAtA, i, uint64(len(m.Disputer)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintJob(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintJob(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Fee != 0 {
		i = encodeVarintJob(dAtA, i, uint64(m.Fee))
		i--
		dAtA[i] = 0x20
	}
	if len(m.MinerId) > 0 {
		i -= len(m.MinerId)
		copy(dAtA[i:], m.MinerId)
		i = encodeVarintJob(dAtA, i, uint64(len(m.MinerId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Client) > 0 {
		i -= len(m.Client)
		copy(dAtA[i:], m.Client)
		i = encodeVarintJob(dAtA, i, uint64(len(m.Client)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.JobId) > 0 {
		i -= len(m.JobId)
		copy(dAtA[i:], m.JobId)
		i = encodeVarintJob(dAtA, i, uint64(len(m.JobId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SlashRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SlashRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SlashRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintJob(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.MinerId) > 0 {
		i -= len(m.MinerId)
		copy(dAtA[i:], m.MinerId)
		i = encodeVarintJob(dAtA, i, uint64(len(m.MinerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintJob(dAtA []byte, offset int, v uint64) int {
	offset -= sovJob(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Job) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.JobId)
	if l > 0 {
		n += 1 + l + sovJob(uint64(l))
	}
	l = len(m.Client)
	if l > 0 {
		n += 1 + l + sovJob(uint64(l))
	}
	l = len(m.MinerId)
	if l > 0 {
		n += 1 + l + sovJob(uint64(l))
	}
	if m.Fee != 0 {
		n += 1 + sovJob(uint64(m.Fee))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovJob(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovJob(uint64(l))
	}
	l = len(m.Disputer)
	if l > 0 {
		n += 1 + l + sovJob(uint64(l))
	}
	if m.DisputeBond != 0 {
		n += 1 + sovJob(uint64(m.DisputeBond))
	}
	if m.DisputeHeight != 0 {
		n += 1 + sovJob(uint64(m.DisputeHeight))
	}
	if len(m.SlashRecords) > 0 {
		for _, e := range m.SlashRecords {
			l = e.Size()
			n += 1 + l + sovJob(uint64(l))
		}
	}
	if m.AuditDistinctVoters != 0 {
		n += 1 + sovJob(uint64(m.AuditDistinctVoters))
	}
	if m.AuditVoters != 0 {
		n += 1 + sovJob(uint64(m.AuditVoters))
	}
	if m.AuditMaxOperatorVotes != 0 {
		n += 1 + sovJob(uint64(m.AuditMaxOperatorVotes))
	}
	return n
}

func (m *SlashRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MinerId)
	if l > 0 {
		n += 1 + l + sovJob(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovJob(uint64(m.Amount))
	}
	return n
}

func sovJob(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozJob(x uint64) (n int) {
	return sovJob(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Job) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJob
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Job: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Job: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJob
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJob
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJob
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Client", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJob
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJob
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJob
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Client = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJob
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJob
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJob
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			m.Fee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJob
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Fee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJob
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJob
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJob
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJob
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJob
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJob
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Disputer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJob
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJob
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJob
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Disputer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeBond", wireType)
			}
			m.DisputeBond = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJob
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DisputeBond |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeHeight", wireType)
			}
			m.DisputeHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJob
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DisputeHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJob
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthJob
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthJob
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SlashRecords = append(m.SlashRecords, SlashRecord{})
			if err := m.SlashRecords[len(m.SlashRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditDistinctVoters", wireType)
			}
			m.AuditDistinctVoters = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJob
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuditDistinctVoters |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditVoters", wireType)
			}
			m.AuditVoters = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJob
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuditVoters |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditMaxOperatorVotes", wireType)
			}
			m.AuditMaxOperatorVotes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJob
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuditMaxOperatorVotes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipJob(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthJob
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SlashRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowJob
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SlashRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SlashRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJob
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthJob
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthJob
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowJob
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipJob(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthJob
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipJob(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowJob
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowJob
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowJob
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthJob
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupJob
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthJob
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthJob        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowJob          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupJob = fmt.Errorf("proto: unexpected end of group")
)
