// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dendra/jobs/v1/miner.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Miner is the on-chain registration of a compute provider: its identity, its bonded stake and the
// public keys everything else is verified against.
type Miner struct {
	MinerId        string `protobuf:"bytes,1,opt,name=miner_id,json=minerId,proto3" json:"miner_id,omitempty"`
	Operator       string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Region         string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Stake          uint64 `protobuf:"varint,4,opt,name=stake,proto3" json:"stake,omitempty"`
	Creator        string `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Demand         uint64 `protobuf:"varint,6,opt,name=demand,proto3" json:"demand,omitempty"`
	SubsidyClaimed uint64 `protobuf:"varint,7,opt,name=subsidy_claimed,json=subsidyClaimed,proto3" json:"subsidy_claimed,omitempty"`
	// X25519 public key (hex, 32 bytes) anchored at registration. Clients encrypt payloads to the key
	// the miner committed to on-chain, never to one handed out by a relay: without this anchor, the
	// party that forwards the job can substitute its own key and read every prompt it carries.
	EncPubkey string `protobuf:"bytes,8,opt,name=enc_pubkey,json=encPubkey,proto3" json:"enc_pubkey,omitempty"`
	// Ed25519 VRF public key (hex, 32 bytes) anchored at registration. Every ECVRF proof this miner
	// submits (availability challenge, beacon) verifies against it.
	VrfPubkey string `protobuf:"bytes,9,opt,name=vrf_pubkey,json=vrfPubkey,proto3" json:"vrf_pubkey,omitempty"`
}

func (m *Miner) Reset()         { *m = Miner{} }
func (m *Miner) String() string { return proto.CompactTextString(m) }
func (*Miner) ProtoMessage()    {}
func (*Miner) Descriptor() ([]byte, []int) {
	return fileDescriptor_8afd01c063091b60, []int{0}
}
func (m *Miner) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Miner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Miner.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Miner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Miner.Merge(m, src)
}
func (m *Miner) XXX_Size() int {
	return m.Size()
}
func (m *Miner) XXX_DiscardUnknown() {
	xxx_messageInfo_Miner.DiscardUnknown(m)
}

var xxx_messageInfo_Miner proto.InternalMessageInfo

func (m *Miner) GetMinerId() string {
	if m != nil {
		return m.MinerId
	}
	return ""
}

func (m *Miner) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Miner) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Miner) GetStake() uint64 {
	if m != nil {
		return m.Stake
	}
	return 0
}

func (m *Miner) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Miner) GetDemand() uint64 {
	if m != nil {
		return m.Demand
	}
	return 0
}

func (m *Miner) GetSubsidyClaimed() uint64 {
	if m != nil {
		return m.SubsidyClaimed
	}
	return 0
}

func (m *Miner) GetEncPubkey() string {
	if m != nil {
		return m.EncPubkey
	}
	return ""
}

func (m *Miner) GetVrfPubkey() string {
	if m != nil {
		return m.VrfPubkey
	}
	return ""
}

func init() {
	proto.RegisterType((*Miner)(nil), "dendra.jobs.v1.Miner")
}

func init() { proto.RegisterFile("dendra/jobs/v1/miner.proto", fileDescriptor_8afd01c063091b60) }

var fileDescriptor_8afd01c063091b60 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0x3f, 0x4b, 0x03, 0x31,
	0x18, 0xc6, 0x9b, 0xda, 0xbf, 0x19, 0x2a, 0x04, 0x91, 0x58, 0x30, 0x14, 0x17, 0xbb, 0x78, 0xa1,
	0xb8, 0x39, 0xaa, 0x8b, 0x83, 0x22, 0xc5, 0xc9, 0xa5, 0xe4, 0x92, 0xb7, 0x6d, 0xac, 0x97, 0x1c,
	0xb9, 0xf4, 0xb4, 0x1f, 0xc0, 0xdd, 0x8f, 0xe5, 0xd8, 0xd1, 0x51, 0xda, 0x2f, 0x22, 0x97, 0x9c,
	0x8e, 0xbf, 0xe7, 0xf7, 0xe6, 0x09, 0x3c, 0x78, 0xa8, 0xc0, 0x28, 0x27, 0xf8, 0x8b, 0x4d, 0x0b,
	0x5e, 0x4e, 0x78, 0xa6, 0x0d, 0xb8, 0x24, 0x77, 0xd6, 0x5b, 0x32, 0x88, 0x2e, 0xa9, 0x5c, 0x52,
	0x4e, 0xce, 0x3e, 0x9a, 0xb8, 0x7d, 0x5f, 0x79, 0x72, 0x82, 0x7b, 0xe1, 0x70, 0xa6, 0x15, 0x45,
	0x23, 0x34, 0xee, 0x4f, 0xbb, 0x81, 0xef, 0x14, 0x19, 0xe2, 0x9e, 0xcd, 0xc1, 0x09, 0x6f, 0x1d,
	0x6d, 0x06, 0xf5, 0xcf, 0xe4, 0x18, 0x77, 0x1c, 0x2c, 0xb4, 0x35, 0xf4, 0x20, 0x98, 0x9a, 0xc8,
	0x11, 0x6e, 0x17, 0x5e, 0xac, 0x80, 0xb6, 0x46, 0x68, 0xdc, 0x9a, 0x46, 0x20, 0x14, 0x77, 0xa5,
	0x83, 0x50, 0xd4, 0x8e, 0x7f, 0xd4, 0x58, 0xf5, 0x28, 0xc8, 0x84, 0x51, 0xb4, 0x13, 0x1e, 0xd4,
	0x44, 0xce, 0xf1, 0x61, 0xb1, 0x4e, 0x0b, 0xad, 0x36, 0x33, 0xf9, 0x2a, 0x74, 0x06, 0x8a, 0x76,
	0xc3, 0xc1, 0xa0, 0x8e, 0x6f, 0x62, 0x4a, 0x4e, 0x31, 0x06, 0x23, 0x67, 0xf9, 0x3a, 0x5d, 0xc1,
	0x86, 0xf6, 0x42, 0x7b, 0x1f, 0x8c, 0x7c, 0x0c, 0x41, 0xa5, 0x4b, 0x37, 0xff, 0xd3, 0xfd, 0xa8,
	0x4b, 0x37, 0x8f, 0xfa, 0xfa, 0xe9, 0x6b, 0xc7, 0xd0, 0x76, 0xc7, 0xd0, 0xcf, 0x8e, 0xa1, 0xcf,
	0x3d, 0x6b, 0x6c, 0xf7, 0xac, 0xf1, 0xbd, 0x67, 0x8d, 0xe7, 0xab, 0x85, 0xf6, 0xcb, 0x75, 0x9a,
	0x48, 0x9b, 0xf1, 0xdb, 0x30, 0xde, 0x03, 0xf8, 0x37, 0xeb, 0x56, 0x3c, 0x4e, 0x79, 0x61, 0x6a,
	0x94, 0x4b, 0xa1, 0x0d, 0x7f, 0x8f, 0xb3, 0xfb, 0x4d, 0x0e, 0x45, 0xda, 0x09, 0xa3, 0x5f, 0xfe,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x20, 0x07, 0xbf, 0xca, 0x92, 0x01, 0x00, 0x00,
}

func (m *Miner) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Miner) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Miner) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VrfPubkey) > 0 {
		i -= len(m.VrfPubkey)
		copy(dAtA[i:], m.VrfPubkey)
		i = encodeVarintMiner(dAtA, i, uint64(len(m.VrfPubkey)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.EncPubkey) > 0 {
		i -= len(m.EncPubkey)
		copy(dAtA[i:], m.EncPubkey)
		i = encodeVarintMiner(dAtA, i, uint64(len(m.EncPubkey)))
		i--
		dAtA[i] = 0x42
	}
	if m.SubsidyClaimed != 0 {
		i = encodeVarintMiner(dAtA, i, uint64(m.SubsidyClaimed))
		i--
		dAtA[i] = 0x38
	}
	if m.Demand != 0 {
		i = encodeVarintMiner(dAtA, i, uint64(m.Demand))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintMiner(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Stake != 0 {
		i = encodeVarintMiner(dAtA, i, uint64(m.Stake))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Region) > 0 {
		i -= len(m.Region)
		copy(dAtA[i:], m.Region)
		i = encodeVarintMiner(dAtA, i, uint64(len(m.Region)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintMiner(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MinerId) > 0 {
		i -= len(m.MinerId)
		copy(dAtA[i:], m.MinerId)
		i = encodeVarintMiner(dAtA, i, uint64(len(m.MinerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMiner(dAtA []byte, offset int, v uint64) int {
	offset -= sovMiner(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Miner) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MinerId)
	if l > 0 {
		n += 1 + l + sovMiner(uint64(l))
	}
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovMiner(uint64(l))
	}
	l = len(m.Region)
	if l > 0 {
		n += 1 + l + sovMiner(uint64(l))
	}
	if m.Stake != 0 {
		n += 1 + sovMiner(uint64(m.Stake))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovMiner(uint64(l))
	}
	if m.Demand != 0 {
		n += 1 + sovMiner(uint64(m.Demand))
	}
	if m.SubsidyClaimed != 0 {
		n += 1 + sovMiner(uint64(m.SubsidyClaimed))
	}
	l = len(m.EncPubkey)
	if l > 0 {
		n += 1 + l + sovMiner(uint64(l))
	}
	l = len(m.VrfPubkey)
	if l > 0 {
		n += 1 + l + sovMiner(uint64(l))
	}
	return n
}

func sovMiner(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMiner(x uint64) (n int) {
	return sovMiner(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Miner) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMiner
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Miner: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Miner: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMiner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMiner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMiner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMiner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Region", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMiner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMiner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Region = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stake", wireType)
			}
			m.Stake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Stake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMiner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMiner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Demand", wireType)
			}
			m.Demand = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Demand |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubsidyClaimed", wireType)
			}
			m.SubsidyClaimed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubsidyClaimed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncPubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMiner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMiner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncPubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VrfPubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMiner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMiner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VrfPubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMiner(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMiner
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMiner(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMiner
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMiner
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMiner
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMiner
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMiner
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMiner        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMiner          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMiner = fmt.Errorf("proto: unexpected end of group")
)
