// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dendra/jobs/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params holds the economic and security parameters of the jobs module (ADR-017, ADR-018).
// Every *_bps field is expressed in basis points: 1 bps = 1/10000, so 10000 = 100%.
//
// Many fields below are DORMANT at their zero value: the keeper then reproduces the behaviour that
// existed before the feature was introduced. Turning one on is a governance act, and each such
// field states what changes when it stops being zero.
type Params struct {
	MinStake           uint64 `protobuf:"varint,1,opt,name=min_stake,json=minStake,proto3" json:"min_stake,omitempty"`
	ProtocolFeeBps     uint64 `protobuf:"varint,2,opt,name=protocol_fee_bps,json=protocolFeeBps,proto3" json:"protocol_fee_bps,omitempty"`
	ValidatorRewardBps uint64 `protobuf:"varint,3,opt,name=validator_reward_bps,json=validatorRewardBps,proto3" json:"validator_reward_bps,omitempty"`
	TeamFeeBps         uint64 `protobuf:"varint,4,opt,name=team_fee_bps,json=teamFeeBps,proto3" json:"team_fee_bps,omitempty"`
	// Fraction of the miner's share HELD BACK at settlement; 3000 = 30%. Read by the authority-gated
	// legacy settlement only, where it splits the payment between `pools.MinerPaid` and
	// `pools.MinerLocked`. There is NO release schedule: what it holds back is retained, not vested.
	MinerVestBps uint64 `protobuf:"varint,5,opt,name=miner_vest_bps,json=minerVestBps,proto3" json:"miner_vest_bps,omitempty"`
	SlashLeakBps uint64 `protobuf:"varint,7,opt,name=slash_leak_bps,json=slashLeakBps,proto3" json:"slash_leak_bps,omitempty"`
	// RESERVED. Epoch length for this module, read by nothing: the epoch that actually drives
	// emission is a parameter of the emission module, and availability has its own period in
	// avail_epoch_blocks. Setting this field changes no behaviour here.
	EpochBlocks uint64 `protobuf:"varint,10,opt,name=epoch_blocks,json=epochBlocks,proto3" json:"epoch_blocks,omitempty"`
	// Work gate on the subsidy: a miner can claim at most demand * work_gate_bps / 10000, so 15000
	// caps the claim at 1.5x the non-recoverable demand it actually served. The gate is what keeps a
	// wash trade negative-EV — buying your own demand must cost more than the subsidy it unlocks.
	WorkGateBps uint64 `protobuf:"varint,11,opt,name=work_gate_bps,json=workGateBps,proto3" json:"work_gate_bps,omitempty"`
	FeeBurnBps  uint64 `protobuf:"varint,13,opt,name=fee_burn_bps,json=feeBurnBps,proto3" json:"fee_burn_bps,omitempty"`
	// Off by default. When on, CreateCommit requires a model that is registered and active, so a
	// miner cannot bill for a model the network has never seen.
	EnforceModelRegistry bool `protobuf:"varint,14,opt,name=enforce_model_registry,json=enforceModelRegistry,proto3" json:"enforce_model_registry,omitempty"`
	// 0 (default): the committee seed is fixed when the job opens, which is adequate only on a
	// development network. >0: the seed is REVEALED N blocks LATER, taken from the app hash of a
	// future block. A seed knowable at open time lets the party choosing when to open a job grind it
	// until the committee draw favours them; a seed that does not exist yet cannot be ground.
	CommitteeRevealDelay uint64 `protobuf:"varint,15,opt,name=committee_reveal_delay,json=committeeRevealDelay,proto3" json:"committee_reveal_delay,omitempty"`
	// 0 (default): availability is off. >0: period, in blocks, of the availability challenge and of
	// the payout drawn from the availability pool.
	AvailEpochBlocks uint64 `protobuf:"varint,16,opt,name=avail_epoch_blocks,json=availEpochBlocks,proto3" json:"avail_epoch_blocks,omitempty"`
	// Fraction of the availability pool paid out per availability epoch (1/10000); 0 pays nothing.
	AvailPayoutBps uint64 `protobuf:"varint,17,opt,name=avail_payout_bps,json=availPayoutBps,proto3" json:"avail_payout_bps,omitempty"`
	// Off by default. When on, only miners that served real demand (demand > 0) draw from the
	// availability pool. Liveness alone can be farmed by a process holding no GPU at all, so paying
	// for liveness alone funds exactly the participant the pool is meant to exclude.
	AvailRequireDemand bool `protobuf:"varint,18,opt,name=avail_require_demand,json=availRequireDemand,proto3" json:"avail_require_demand,omitempty"`
	// VRF public key (hex, 32 bytes) of the beacon authority. Empty disables it, and seeds fall back
	// to app-hash revelation.
	VrfBeaconPubkey string `protobuf:"bytes,19,opt,name=vrf_beacon_pubkey,json=vrfBeaconPubkey,proto3" json:"vrf_beacon_pubkey,omitempty"`
	// 0 (default): legacy seed (height:time / app hash). 1: DECENTRALIZED VRF, the seed aggregated
	// from validator vote extensions. A single-source seed is only as unpredictable as the party that
	// produces it; aggregation removes that party.
	CommitteeSeedSource uint64 `protobuf:"varint,20,opt,name=committee_seed_source,json=committeeSeedSource,proto3" json:"committee_seed_source,omitempty"`
	// Fraud proof / dispute: bonded re-adjudication of a settled verdict (see
	// docs/DISPUTE-FRAUDPROOF.md). Off by default.
	DisputeWindow uint64 `protobuf:"varint,21,opt,name=dispute_window,json=disputeWindow,proto3" json:"dispute_window,omitempty"`
	// Bond (udndr) escrowed to challenge a verdict. The bond is what makes the dispute permissionless
	// without making it free: anyone may contest, a losing challenger pays for the network's time.
	DisputeBond uint64 `protobuf:"varint,22,opt,name=dispute_bond,json=disputeBond,proto3" json:"dispute_bond,omitempty"`
	// Optimistic verification by VRF sampling (ADR-025). Dormant by default.
	// 0 (default): redundant verification, k = 3 miners answer every job and are compared.
	// 1: optimistic, k = 1 answers, a sampled subset is audited, and a caught liar is slashed hard.
	// Optimistic mode trades redundancy for a penalty: the deterrent must exceed what cheating pays,
	// which is why audit_sample_bps and slash_leak_bps are checked against each other at open time.
	VerificationMode uint64 `protobuf:"varint,23,opt,name=verification_mode,json=verificationMode,proto3" json:"verification_mode,omitempty"`
	AuditSampleBps   uint64 `protobuf:"varint,24,opt,name=audit_sample_bps,json=auditSampleBps,proto3" json:"audit_sample_bps,omitempty"`
	// Optional refinements of the audit draw, all dormant at 0.
	// 0: off. >0: reference fee. The effective rate becomes audit_sample_bps * (1 + fee/reference),
	// capped at 10000, so a job worth more to cheat on is audited more often.
	AuditAdaptive uint64 `protobuf:"varint,25,opt,name=audit_adaptive,json=auditAdaptive,proto3" json:"audit_adaptive,omitempty"`
	// 0: off. N: a miner is audited at 100% over its first N optimistic jobs. A fresh identity is
	// exactly the one whose behaviour is unknown, so a Sybil pays full verification before it can
	// benefit from sampling.
	AuditProbationJobs uint64 `protobuf:"varint,26,opt,name=audit_probation_jobs,json=auditProbationJobs,proto3" json:"audit_probation_jobs,omitempty"`
	// 0: off. >0: an audit still unresolved after N blocks is auto-vindicated at end of block. An
	// audit that no one resolves would otherwise hold the payment forever; liveness of the settlement
	// path must not depend on a juror showing up.
	AuditResolveTimeout uint64 `protobuf:"varint,27,opt,name=audit_resolve_timeout,json=auditResolveTimeout,proto3" json:"audit_resolve_timeout,omitempty"`
	// Full-compliance levers of ADR-028: three governable parameters, all dormant at 0. While they
	// are 0 the keeper reproduces the earlier behaviour exactly, so enabling them is a deliberate
	// governance act and never a side effect of an upgrade.
	//
	// 0 (dormant): a silent primary costs only the light clawback. >0: an ADDITIONAL stake penalty
	// (stake * bps / 10000, refundable, routed to the treasury) on the no-quorum clawback. A primary
	// that stays silent when its answer is questioned otherwise pays less than one that answers and
	// is caught.
	SilenceSlashBps uint64 `protobuf:"varint,28,opt,name=silence_slash_bps,json=silenceSlashBps,proto3" json:"silence_slash_bps,omitempty"`
	// 0 (dormant): restitution goes through governance. >0: number of blocks allowed for a late
	// reveal, making the appeal permissionless. RESERVED: the value is stored and validated but not
	// yet consumed by the state machine, so setting it has no effect on adjudication today.
	AppealWindow uint64 `protobuf:"varint,29,opt,name=appeal_window,json=appealWindow,proto3" json:"appeal_window,omitempty"`
	// 0 (dormant): the participation floor is the default ceil(CommitteeSize/2)+1. >0: a governed
	// floor, expressed as a WHOLE NUMBER of distinct fresh judges required before a hard slash. A
	// floor in seats rather than in fractions is what a quorum check can be read against directly.
	AuditMinQuorum uint64 `protobuf:"varint,30,opt,name=audit_min_quorum,json=auditMinQuorum,proto3" json:"audit_min_quorum,omitempty"`
	// Fee hold: makes the optimistic payment genuinely provisional.
	// 0 (dormant): the optimistic payment is released in full, immediately. >0: that fraction of the
	// payment is HELD by the module until the audit window closes, then released to the primary if it
	// is vindicated or never audited, and refunded to the client otherwise. The refund is always
	// taken from the HELD FEE, never from the bond: a bond answers for misconduct, not for a payment
	// the protocol chose to advance.
	HoldBps uint64 `protobuf:"varint,31,opt,name=hold_bps,json=holdBps,proto3" json:"hold_bps,omitempty"`
	// Floor on the number of contributors below which the decentralized seed is not decentralized
	// enough to draw a committee on an incentivized network.
	// 0 (dormant): no minimum, and only the total absence of a seed raises an alert. >0: when
	// committee_seed_source = 1 and the seed has fewer than N contributors, the chain raises a VISIBLE
	// alert and falls back to the legacy seed. It never halts: a chain that stops on a weak seed
	// converts a randomness problem into an availability problem.
	// Suggested setting for an incentivized testnet: ceil(2/3 of the expected validator set), fixed
	// for the run. A live ceil(2N/3) tracking the actual set requires wiring the staking keeper.
	// Raise it as the validator set grows.
	CommitteeMinVrfContributors uint64 `protobuf:"varint,32,opt,name=committee_min_vrf_contributors,json=committeeMinVrfContributors,proto3" json:"committee_min_vrf_contributors,omitempty"`
	// Slashable availability by VRF-sampled challenge, the "proof of availability" of ADR-022. Each
	// epoch the keeper draws a subset of bonded miners from the decentralized seed and sends each one
	// a challenge INDISTINGUISHABLE from a real job; a failure (no answer by the deadline, or an
	// answer that is semantically wrong) counts against the miner, and a bounded slash follows only
	// once a quorum of failures is reached.
	//
	// All six fields are dormant at 0 and stay inert until avail_epoch_blocks > 0 AND they are set.
	//
	// 0 (dormant): the challenge answer is not checked semantically. >0: cosine threshold (1/10000)
	// below which the answer is judged wrong, using the same comparison as semantic verification.
	AvailThresholdBps uint64 `protobuf:"varint,33,opt,name=avail_threshold_bps,json=availThresholdBps,proto3" json:"avail_threshold_bps,omitempty"`
	// 0 (dormant): no deadline, so no challenge is ever due. >0: blocks the challenged miner has to
	// answer before a FAILURE is recorded.
	AvailDeadlineBlocks uint64 `protobuf:"varint,34,opt,name=avail_deadline_blocks,json=availDeadlineBlocks,proto3" json:"avail_deadline_blocks,omitempty"`
	// 0 (dormant): availability never slashes. >0: fraction of stake (1/10000) slashed once the
	// failure quorum is reached.
	AvailSlashBps uint64 `protobuf:"varint,35,opt,name=avail_slash_bps,json=availSlashBps,proto3" json:"avail_slash_bps,omitempty"`
	// 0 (dormant): no upper bound. >0: ABSOLUTE cap (udndr) on one availability slash, so the applied
	// amount is min(stake * avail_slash_bps / 10000, avail_slash_max). The cap bounds what a
	// misconfigured threshold can cost the largest miner on the network.
	AvailSlashMax uint64 `protobuf:"varint,36,opt,name=avail_slash_max,json=availSlashMax,proto3" json:"avail_slash_max,omitempty"`
	// 0 (dormant): empty window, so the quorum is never reached. >0: length, in EPOCHS, of the
	// sliding window over which one miner's failures are counted.
	AvailFailWindow uint64 `protobuf:"varint,37,opt,name=avail_fail_window,json=availFailWindow,proto3" json:"avail_fail_window,omitempty"`
	// 0 (dormant): never slashes. >0: number of FAILURES within avail_fail_window required to trigger
	// the slash. A single missed challenge is a network hiccup, not evidence of absence, and slashing
	// on one sample bills honest operators for the transport layer.
	AvailFailK uint64 `protobuf:"varint,38,opt,name=avail_fail_k,json=availFailK,proto3" json:"avail_fail_k,omitempty"`
	// Governable VITALITY windows (ADR-034 section 5). These are values that will have to be
	// recalibrated against real data — the p99 of the interval between commits of honest miners —
	// and a value known in advance to need recalibration must not require a binary upgrade.
	// 0 (dormant): the compiled defaults in miner_vitality.go apply (juror freshness about 3 days,
	// 259200 blocks; pruning about 7 days, 604800).
	// Direction of safety: too short BILLS AN OUTAGE TO AN HONEST MINER, which is the failure these
	// windows exist to avoid; too long merely under-punishes.
	JurorFreshnessBlocks uint64 `protobuf:"varint,39,opt,name=juror_freshness_blocks,json=jurorFreshnessBlocks,proto3" json:"juror_freshness_blocks,omitempty"`
	MinerPruneBlocks     uint64 `protobuf:"varint,40,opt,name=miner_prune_blocks,json=minerPruneBlocks,proto3" json:"miner_prune_blocks,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea3dd43f1cc66bdf, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMinStake() uint64 {
	if m != nil {
		return m.MinStake
	}
	return 0
}

func (m *Params) GetProtocolFeeBps() uint64 {
	if m != nil {
		return m.ProtocolFeeBps
	}
	return 0
}

func (m *Params) GetValidatorRewardBps() uint64 {
	if m != nil {
		return m.ValidatorRewardBps
	}
	return 0
}

func (m *Params) GetTeamFeeBps() uint64 {
	if m != nil {
		return m.TeamFeeBps
	}
	return 0
}

func (m *Params) GetMinerVestBps() uint64 {
	if m != nil {
		return m.MinerVestBps
	}
	return 0
}

func (m *Params) GetSlashLeakBps() uint64 {
	if m != nil {
		return m.SlashLeakBps
	}
	return 0
}

func (m *Params) GetEpochBlocks() uint64 {
	if m != nil {
		return m.EpochBlocks
	}
	return 0
}

func (m *Params) GetWorkGateBps() uint64 {
	if m != nil {
		return m.WorkGateBps
	}
	return 0
}

func (m *Params) GetFeeBurnBps() uint64 {
	if m != nil {
		return m.FeeBurnBps
	}
	return 0
}

func (m *Params) GetEnforceModelRegistry() bool {
	if m != nil {
		return m.EnforceModelRegistry
	}
	return false
}

func (m *Params) GetCommitteeRevealDelay() uint64 {
	if m != nil {
		return m.CommitteeRevealDelay
	}
	return 0
}

func (m *Params) GetAvailEpochBlocks() uint64 {
	if m != nil {
		return m.AvailEpochBlocks
	}
	return 0
}

func (m *Params) GetAvailPayoutBps() uint64 {
	if m != nil {
		return m.AvailPayoutBps
	}
	return 0
}

func (m *Params) GetAvailRequireDemand() bool {
	if m != nil {
		return m.AvailRequireDemand
	}
	return false
}

func (m *Params) GetVrfBeaconPubkey() string {
	if m != nil {
		return m.VrfBeaconPubkey
	}
	return ""
}

func (m *Params) GetCommitteeSeedSource() uint64 {
	if m != nil {
		return m.CommitteeSeedSource
	}
	return 0
}

func (m *Params) GetDisputeWindow() uint64 {
	if m != nil {
		return m.DisputeWindow
	}
	return 0
}

func (m *Params) GetDisputeBond() uint64 {
	if m != nil {
		return m.DisputeBond
	}
	return 0
}

func (m *Params) GetVerificationMode() uint64 {
	if m != nil {
		return m.VerificationMode
	}
	return 0
}

func (m *Params) GetAuditSampleBps() uint64 {
	if m != nil {
		return m.AuditSampleBps
	}
	return 0
}

func (m *Params) GetAuditAdaptive() uint64 {
	if m != nil {
		return m.AuditAdaptive
	}
	return 0
}

func (m *Params) GetAuditProbationJobs() uint64 {
	if m != nil {
		return m.AuditProbationJobs
	}
	return 0
}

func (m *Params) GetAuditResolveTimeout() uint64 {
	if m != nil {
		return m.AuditResolveTimeout
	}
	return 0
}

func (m *Params) GetSilenceSlashBps() uint64 {
	if m != nil {
		return m.SilenceSlashBps
	}
	return 0
}

func (m *Params) GetAppealWindow() uint64 {
	if m != nil {
		return m.AppealWindow
	}
	return 0
}

func (m *Params) GetAuditMinQuorum() uint64 {
	if m != nil {
		return m.AuditMinQuorum
	}
	return 0
}

func (m *Params) GetHoldBps() uint64 {
	if m != nil {
		return m.HoldBps
	}
	return 0
}

func (m *Params) GetCommitteeMinVrfContributors() uint64 {
	if m != nil {
		return m.CommitteeMinVrfContributors
	}
	return 0
}

func (m *Params) GetAvailThresholdBps() uint64 {
	if m != nil {
		return m.AvailThresholdBps
	}
	return 0
}

func (m *Params) GetAvailDeadlineBlocks() uint64 {
	if m != nil {
		return m.AvailDeadlineBlocks
	}
	return 0
}

func (m *Params) GetAvailSlashBps() uint64 {
	if m != nil {
		return m.AvailSlashBps
	}
	return 0
}

func (m *Params) GetAvailSlashMax() uint64 {
	if m != nil {
		return m.AvailSlashMax
	}
	return 0
}

func (m *Params) GetAvailFailWindow() uint64 {
	if m != nil {
		return m.AvailFailWindow
	}
	return 0
}

func (m *Params) GetAvailFailK() uint64 {
	if m != nil {
		return m.AvailFailK
	}
	return 0
}

func (m *Params) GetJurorFreshnessBlocks() uint64 {
	if m != nil {
		return m.JurorFreshnessBlocks
	}
	return 0
}

func (m *Params) GetMinerPruneBlocks() uint64 {
	if m != nil {
		return m.MinerPruneBlocks
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "dendra.jobs.v1.Params")
}

func init() { proto.RegisterFile("dendra/jobs/v1/params.proto", fileDescriptor_ea3dd43f1cc66bdf) }

var fileDescriptor_ea3dd43f1cc66bdf = []byte{
	// 1003 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x55, 0xd1, 0x72, 0x1b, 0x35,
	0x17, 0x8e, 0xff, 0xdf, 0x24, 0x8e, 0x6a, 0x27, 0xf6, 0xc6, 0x2d, 0xdb, 0x84, 0xba, 0x6e, 0xda,
	0x14, 0x4f, 0x29, 0x31, 0x05, 0xae, 0x7a, 0x87, 0x1b, 0xc2, 0x4c, 0x20, 0x4c, 0xd8, 0x64, 0xca,
	0x0c, 0x37, 0x1a, 0xed, 0xee, 0x71, 0xac, 0x7a, 0x57, 0xda, 0x4a, 0xda, 0x4d, 0xf2, 0x0a, 0x5c,
	0x31, 0x3c, 0x01, 0x8f, 0xc0, 0x63, 0x70, 0xd9, 0x4b, 0x2e, 0x99, 0xe4, 0x02, 0x1e, 0x83, 0xd1,
	0x91, 0xd6, 0x31, 0xbd, 0xd9, 0x59, 0x7d, 0xdf, 0x77, 0xa4, 0xa3, 0xef, 0x48, 0x47, 0x64, 0x27,
	0x05, 0x91, 0x2a, 0x36, 0x7e, 0x23, 0x63, 0x3d, 0xae, 0x5e, 0x8c, 0x0b, 0xa6, 0x58, 0xae, 0xf7,
	0x0b, 0x25, 0x8d, 0x0c, 0x36, 0x1c, 0xb9, 0x6f, 0xc9, 0xfd, 0xea, 0xc5, 0x76, 0x8f, 0xe5, 0x5c,
	0xc8, 0x31, 0x7e, 0x9d, 0x64, 0xbb, 0x7f, 0x2e, 0xcf, 0x25, 0xfe, 0x8e, 0xed, 0x9f, 0x43, 0x77,
	0x7f, 0xed, 0x90, 0xd5, 0x13, 0x9c, 0x29, 0xd8, 0x21, 0xeb, 0x39, 0x17, 0x54, 0x1b, 0x36, 0x87,
	0xb0, 0x31, 0x6c, 0x8c, 0x9a, 0x51, 0x2b, 0xe7, 0xe2, 0xd4, 0x8e, 0x83, 0x11, 0xe9, 0x62, 0x40,
	0x22, 0x33, 0x3a, 0x05, 0xa0, 0x71, 0xa1, 0xc3, 0xff, 0xa1, 0x66, 0xa3, 0xc6, 0x0f, 0x01, 0x26,
	0x85, 0x0e, 0x3e, 0x23, 0xfd, 0x8a, 0x65, 0x3c, 0x65, 0x46, 0x2a, 0xaa, 0xe0, 0x82, 0xa9, 0x14,
	0xd5, 0xff, 0x47, 0x75, 0xb0, 0xe0, 0x22, 0xa4, 0x6c, 0xc4, 0x90, 0xb4, 0x0d, 0xb0, 0x7c, 0x31,
	0x6f, 0x13, 0x95, 0xc4, 0x62, 0x7e, 0xce, 0x27, 0x64, 0x23, 0xe7, 0x02, 0x14, 0xad, 0x40, 0x1b,
	0xd4, 0x7c, 0x80, 0x9a, 0x36, 0xa2, 0xaf, 0x41, 0x1b, 0xaf, 0xd2, 0x19, 0xd3, 0x33, 0x9a, 0x01,
	0x9b, 0xa3, 0x6a, 0xcd, 0xa9, 0x10, 0xfd, 0x0e, 0xd8, 0xdc, 0xaa, 0x1e, 0x91, 0x36, 0x14, 0x32,
	0x99, 0xd1, 0x38, 0x93, 0xc9, 0x5c, 0x87, 0x04, 0x35, 0x77, 0x10, 0x9b, 0x20, 0x14, 0xec, 0x92,
	0xce, 0x85, 0x54, 0x73, 0x7a, 0xce, 0x8c, 0xcb, 0xe8, 0x8e, 0xd3, 0x58, 0xf0, 0x1b, 0x66, 0xc0,
	0x27, 0x8d, 0xf9, 0x96, 0x4a, 0xa0, 0xa4, 0xe3, 0x92, 0x9e, 0x02, 0x4c, 0x4a, 0x25, 0xac, 0xe2,
	0x4b, 0x72, 0x0f, 0xc4, 0x54, 0xaa, 0x04, 0x68, 0x2e, 0x53, 0xc8, 0xa8, 0x82, 0x73, 0xae, 0x8d,
	0xba, 0x0a, 0x37, 0x86, 0x8d, 0x51, 0x2b, 0xea, 0x7b, 0xf6, 0xd8, 0x92, 0x91, 0xe7, 0x6c, 0x54,
	0x22, 0xf3, 0x9c, 0x1b, 0x03, 0x40, 0x15, 0x54, 0xc0, 0x32, 0x9a, 0x42, 0xc6, 0xae, 0xc2, 0x4d,
	0x5c, 0xa1, 0xbf, 0x60, 0x23, 0x24, 0x0f, 0x2c, 0x17, 0x3c, 0x27, 0x01, 0xab, 0x18, 0xcf, 0xe8,
	0x7f, 0xb6, 0xd6, 0xc5, 0x88, 0x2e, 0x32, 0x5f, 0x2f, 0xed, 0x6f, 0x44, 0x1c, 0x46, 0x0b, 0x76,
	0x25, 0x4b, 0x67, 0x68, 0xcf, 0x15, 0x13, 0xf1, 0x13, 0x84, 0x7d, 0x31, 0x9d, 0x52, 0xc1, 0xdb,
	0x92, 0x2b, 0xa0, 0x29, 0xe4, 0x4c, 0xa4, 0x61, 0x80, 0x3b, 0x70, 0x6b, 0x46, 0x8e, 0x3a, 0x40,
	0x26, 0x78, 0x46, 0x7a, 0x95, 0x9a, 0xd2, 0x18, 0x58, 0x22, 0x05, 0x2d, 0xca, 0x78, 0x0e, 0x57,
	0xe1, 0xd6, 0xb0, 0x31, 0x5a, 0x8f, 0x36, 0x2b, 0x35, 0x9d, 0x20, 0x7e, 0x82, 0x70, 0xf0, 0x39,
	0xb9, 0x7b, 0xbb, 0x57, 0x0d, 0x90, 0x52, 0x2d, 0x4b, 0x95, 0x40, 0xd8, 0xc7, 0x64, 0xb6, 0x16,
	0xe4, 0x29, 0x40, 0x7a, 0x8a, 0x54, 0xb0, 0x47, 0x36, 0x52, 0xae, 0x8b, 0xd2, 0x00, 0xbd, 0xe0,
	0x22, 0x95, 0x17, 0xe1, 0x5d, 0x14, 0x77, 0x3c, 0xfa, 0x23, 0x82, 0xb6, 0xca, 0xb5, 0x2c, 0x96,
	0x22, 0x0d, 0xef, 0xb9, 0x0a, 0x7a, 0x6c, 0x22, 0x45, 0x1a, 0x7c, 0x42, 0x7a, 0x15, 0x28, 0x3e,
	0xe5, 0x09, 0x33, 0x5c, 0x0a, 0x2c, 0x52, 0xf8, 0xa1, 0xb3, 0x6c, 0x99, 0xb0, 0xf5, 0x41, 0xcb,
	0xca, 0x94, 0x1b, 0xaa, 0x59, 0x5e, 0x64, 0xee, 0x54, 0x84, 0xde, 0x32, 0x8b, 0x9f, 0x22, 0x6c,
	0x2d, 0xdb, 0x23, 0x0e, 0xa1, 0x2c, 0x65, 0x85, 0xe1, 0x15, 0x84, 0xf7, 0x5d, 0x82, 0x88, 0x7e,
	0xe5, 0x41, 0x74, 0x16, 0x65, 0x85, 0x92, 0xb1, 0x4b, 0xc0, 0x5e, 0xde, 0x70, 0xdb, 0x5d, 0x13,
	0xe4, 0x4e, 0x6a, 0xea, 0x48, 0xc6, 0xda, 0xba, 0xe5, 0x22, 0x14, 0x68, 0x99, 0x55, 0x40, 0x0d,
	0xcf, 0x41, 0x96, 0x26, 0xdc, 0x71, 0x6e, 0x21, 0x19, 0x39, 0xee, 0xcc, 0x51, 0xb6, 0x1a, 0x9a,
	0x67, 0x20, 0x12, 0xa0, 0xee, 0x6a, 0xd8, 0xbc, 0x3f, 0x42, 0xfd, 0xa6, 0x27, 0x4e, 0x2d, 0x6e,
	0x13, 0x7f, 0x4c, 0x3a, 0xac, 0x28, 0xec, 0x79, 0xf3, 0xc6, 0x3e, 0x70, 0xb7, 0xc7, 0x81, 0xde,
	0xd7, 0x85, 0x0f, 0xb6, 0x55, 0xbc, 0x2d, 0xa5, 0x2a, 0xf3, 0x70, 0xb0, 0xe4, 0xc3, 0x31, 0x17,
	0x3f, 0x20, 0x1a, 0xdc, 0x27, 0xad, 0x99, 0xcc, 0xdc, 0xdd, 0x7f, 0x88, 0x8a, 0x35, 0x3b, 0xb6,
	0x2b, 0xbd, 0x22, 0x83, 0xdb, 0xba, 0xdb, 0x89, 0xec, 0x89, 0x49, 0xa4, 0x30, 0x8a, 0xc7, 0xa5,
	0x91, 0x4a, 0x87, 0x43, 0x0c, 0xd8, 0x59, 0xa8, 0x8e, 0xb9, 0x78, 0xad, 0xa6, 0xaf, 0x96, 0x24,
	0xc1, 0x3e, 0xd9, 0x72, 0x47, 0xd3, 0xcc, 0x14, 0xe8, 0xc5, 0x52, 0x8f, 0x30, 0xb2, 0x87, 0xd4,
	0x59, 0xcd, 0xd8, 0x45, 0xad, 0x7d, 0xa8, 0x4f, 0x81, 0xa5, 0x19, 0x17, 0x50, 0xdf, 0x92, 0x5d,
	0x6f, 0x9f, 0x25, 0x0f, 0x3c, 0xe7, 0x2f, 0xca, 0x53, 0xb2, 0xe9, 0x62, 0x6e, 0xcd, 0x7b, 0xec,
	0x8b, 0x69, 0xe1, 0x85, 0x75, 0xef, 0xe9, 0x72, 0x76, 0x19, 0x3e, 0x79, 0x5f, 0x77, 0xcc, 0x2e,
	0x6d, 0x39, 0x9c, 0x6e, 0x6a, 0x3f, 0xde, 0xe6, 0x3d, 0x57, 0x0e, 0x24, 0x0e, 0x19, 0xaf, 0x9d,
	0x1e, 0x92, 0xf6, 0x92, 0x76, 0x1e, 0x3e, 0x75, 0x0d, 0x66, 0x21, 0xfb, 0xd6, 0xb6, 0x8a, 0x37,
	0xa5, 0x92, 0x8a, 0x4e, 0xed, 0x36, 0x05, 0x68, 0x5d, 0x6f, 0xe9, 0x63, 0xd7, 0x2a, 0x90, 0x3d,
	0xac, 0x49, 0xbf, 0xa7, 0xe7, 0x24, 0x70, 0xbd, 0xb4, 0x50, 0xe5, 0xad, 0x09, 0x23, 0x77, 0xee,
	0x91, 0x39, 0xb1, 0x84, 0x53, 0xbf, 0x7c, 0xf0, 0xcf, 0x6f, 0x0f, 0x1b, 0x3f, 0xff, 0xfd, 0xfb,
	0xb3, 0xbe, 0x7f, 0x7e, 0x2e, 0xdd, 0x03, 0xe4, 0xde, 0x8c, 0xa3, 0x66, 0x6b, 0xb5, 0xbb, 0x76,
	0xd4, 0x6c, 0xb5, 0xba, 0xeb, 0x47, 0xcd, 0xd6, 0x7a, 0x97, 0x1c, 0x35, 0x5b, 0xed, 0x6e, 0x27,
	0xea, 0x2d, 0xb7, 0x6b, 0x9c, 0x29, 0x6a, 0xd5, 0xad, 0x32, 0x6a, 0x2b, 0x28, 0xa4, 0x32, 0xa0,
	0x70, 0xd4, 0x73, 0x2d, 0x85, 0x26, 0x19, 0x07, 0x61, 0x68, 0xc2, 0x8a, 0xc9, 0xd9, 0x1f, 0xd7,
	0x83, 0xc6, 0xbb, 0xeb, 0x41, 0xe3, 0xaf, 0xeb, 0x41, 0xe3, 0x97, 0x9b, 0xc1, 0xca, 0xbb, 0x9b,
	0xc1, 0xca, 0x9f, 0x37, 0x83, 0x95, 0x9f, 0x5e, 0x9e, 0x73, 0x33, 0x2b, 0xe3, 0xfd, 0x44, 0xe6,
	0xe3, 0x03, 0x4c, 0xe8, 0x7b, 0x30, 0xb6, 0x2d, 0x8f, 0x5d, 0x7a, 0x9f, 0x0a, 0x3f, 0x4c, 0x66,
	0x8c, 0x8b, 0x3a, 0x59, 0x73, 0x55, 0x80, 0x8e, 0x57, 0xf1, 0xa1, 0xfa, 0xe2, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xb4, 0x08, 0x73, 0x8e, 0x49, 0x07, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MinStake != that1.MinStake {
		return false
	}
	if this.ProtocolFeeBps != that1.ProtocolFeeBps {
		return false
	}
	if this.ValidatorRewardBps != that1.ValidatorRewardBps {
		return false
	}
	if this.TeamFeeBps != that1.TeamFeeBps {
		return false
	}
	if this.MinerVestBps != that1.MinerVestBps {
		return false
	}
	if this.SlashLeakBps != that1.SlashLeakBps {
		return false
	}
	if this.EpochBlocks != that1.EpochBlocks {
		return false
	}
	if this.WorkGateBps != that1.WorkGateBps {
		return false
	}
	if this.FeeBurnBps != that1.FeeBurnBps {
		return false
	}
	if this.EnforceModelRegistry != that1.EnforceModelRegistry {
		return false
	}
	if this.CommitteeRevealDelay != that1.CommitteeRevealDelay {
		return false
	}
	if this.AvailEpochBlocks != that1.AvailEpochBlocks {
		return false
	}
	if this.AvailPayoutBps != that1.AvailPayoutBps {
		return false
	}
	if this.AvailRequireDemand != that1.AvailRequireDemand {
		return false
	}
	if this.VrfBeaconPubkey != that1.VrfBeaconPubkey {
		return false
	}
	if this.CommitteeSeedSource != that1.CommitteeSeedSource {
		return false
	}
	if this.DisputeWindow != that1.DisputeWindow {
		return false
	}
	if this.DisputeBond != that1.DisputeBond {
		return false
	}
	if this.VerificationMode != that1.VerificationMode {
		return false
	}
	if this.AuditSampleBps != that1.AuditSampleBps {
		return false
	}
	if this.AuditAdaptive != that1.AuditAdaptive {
		return false
	}
	if this.AuditProbationJobs != that1.AuditProbationJobs {
		return false
	}
	if this.AuditResolveTimeout != that1.AuditResolveTimeout {
		return false
	}
	if this.SilenceSlashBps != that1.SilenceSlashBps {
		return false
	}
	if this.AppealWindow != that1.AppealWindow {
		return false
	}
	if this.AuditMinQuorum != that1.AuditMinQuorum {
		return false
	}
	if this.HoldBps != that1.HoldBps {
		return false
	}
	if this.CommitteeMinVrfContributors != that1.CommitteeMinVrfContributors {
		return false
	}
	if this.AvailThresholdBps != that1.AvailThresholdBps {
		return false
	}
	if this.AvailDeadlineBlocks != that1.AvailDeadlineBlocks {
		return false
	}
	if this.AvailSlashBps != that1.AvailSlashBps {
		return false
	}
	if this.AvailSlashMax != that1.AvailSlashMax {
		return false
	}
	if this.AvailFailWindow != that1.AvailFailWindow {
		return false
	}
	if this.AvailFailK != that1.AvailFailK {
		return false
	}
	if this.JurorFreshnessBlocks != that1.JurorFreshnessBlocks {
		return false
	}
	if this.MinerPruneBlocks != that1.MinerPruneBlocks {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MinerPruneBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinerPruneBlocks))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xc0
	}
	if m.JurorFreshnessBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.JurorFreshnessBlocks))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xb8
	}
	if m.AvailFailK != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AvailFailK))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xb0
	}
	if m.AvailFailWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AvailFailWindow))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xa8
	}
	if m.AvailSlashMax != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AvailSlashMax))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xa0
	}
	if m.AvailSlashBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AvailSlashBps))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x98
	}
	if m.AvailDeadlineBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AvailDeadlineBlocks))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x90
	}
	if m.AvailThresholdBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AvailThresholdBps))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x88
	}
	if m.CommitteeMinVrfContributors != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CommitteeMinVrfContributors))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x80
	}
	if m.HoldBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.HoldBps))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf8
	}
	if m.AuditMinQuorum != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AuditMinQuorum))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf0
	}
	if m.AppealWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AppealWindow))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe8
	}
	if m.SilenceSlashBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SilenceSlashBps))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe0
	}
	if m.AuditResolveTimeout != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AuditResolveTimeout))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd8
	}
	if m.AuditProbationJobs != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AuditProbationJobs))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd0
	}
	if m.AuditAdaptive != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AuditAdaptive))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc8
	}
	if m.AuditSampleBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AuditSampleBps))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc0
	}
	if m.VerificationMode != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.VerificationMode))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb8
	}
	if m.DisputeBond != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DisputeBond))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if m.DisputeWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DisputeWindow))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if m.CommitteeSeedSource != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CommitteeSeedSource))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if len(m.VrfBeaconPubkey) > 0 {
		i -= len(m.VrfBeaconPubkey)
		copy(dAtA[i:], m.VrfBeaconPubkey)
		i = encodeVarintParams(dAtA, i, uint64(len(m.VrfBeaconPubkey)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if m.AvailRequireDemand {
		i--
		if m.AvailRequireDemand {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.AvailPayoutBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AvailPayoutBps))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.AvailEpochBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AvailEpochBlocks))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.CommitteeRevealDelay != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CommitteeRevealDelay))
		i--
		dAtA[i] = 0x78
	}
	if m.EnforceModelRegistry {
		i--
		if m.EnforceModelRegistry {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if m.FeeBurnBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FeeBurnBps))
		i--
		dAtA[i] = 0x68
	}
	if m.WorkGateBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.WorkGateBps))
		i--
		dAtA[i] = 0x58
	}
	if m.EpochBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EpochBlocks))
		i--
		dAtA[i] = 0x50
	}
	if m.SlashLeakBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SlashLeakBps))
		i--
		dAtA[i] = 0x38
	}
	if m.MinerVestBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinerVestBps))
		i--
		dAtA[i] = 0x28
	}
	if m.TeamFeeBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TeamFeeBps))
		i--
		dAtA[i] = 0x20
	}
	if m.ValidatorRewardBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ValidatorRewardBps))
		i--
		dAtA[i] = 0x18
	}
	if m.ProtocolFeeBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ProtocolFeeBps))
		i--
		dAtA[i] = 0x10
	}
	if m.MinStake != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinStake))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinStake != 0 {
		n += 1 + sovParams(uint64(m.MinStake))
	}
	if m.ProtocolFeeBps != 0 {
		n += 1 + sovParams(uint64(m.ProtocolFeeBps))
	}
	if m.ValidatorRewardBps != 0 {
		n += 1 + sovParams(uint64(m.ValidatorRewardBps))
	}
	if m.TeamFeeBps != 0 {
		n += 1 + sovParams(uint64(m.TeamFeeBps))
	}
	if m.MinerVestBps != 0 {
		n += 1 + sovParams(uint64(m.MinerVestBps))
	}
	if m.SlashLeakBps != 0 {
		n += 1 + sovParams(uint64(m.SlashLeakBps))
	}
	if m.EpochBlocks != 0 {
		n += 1 + sovParams(uint64(m.EpochBlocks))
	}
	if m.WorkGateBps != 0 {
		n += 1 + sovParams(uint64(m.WorkGateBps))
	}
	if m.FeeBurnBps != 0 {
		n += 1 + sovParams(uint64(m.FeeBurnBps))
	}
	if m.EnforceModelRegistry {
		n += 2
	}
	if m.CommitteeRevealDelay != 0 {
		n += 1 + sovParams(uint64(m.CommitteeRevealDelay))
	}
	if m.AvailEpochBlocks != 0 {
		n += 2 + sovParams(uint64(m.AvailEpochBlocks))
	}
	if m.AvailPayoutBps != 0 {
		n += 2 + sovParams(uint64(m.AvailPayoutBps))
	}
	if m.AvailRequireDemand {
		n += 3
	}
	l = len(m.VrfBeaconPubkey)
	if l > 0 {
		n += 2 + l + sovParams(uint64(l))
	}
	if m.CommitteeSeedSource != 0 {
		n += 2 + sovParams(uint64(m.CommitteeSeedSource))
	}
	if m.DisputeWindow != 0 {
		n += 2 + sovParams(uint64(m.DisputeWindow))
	}
	if m.DisputeBond != 0 {
		n += 2 + sovParams(uint64(m.DisputeBond))
	}
	if m.VerificationMode != 0 {
		n += 2 + sovParams(uint64(m.VerificationMode))
	}
	if m.AuditSampleBps != 0 {
		n += 2 + sovParams(uint64(m.AuditSampleBps))
	}
	if m.AuditAdaptive != 0 {
		n += 2 + sovParams(uint64(m.AuditAdaptive))
	}
	if m.AuditProbationJobs != 0 {
		n += 2 + sovParams(uint64(m.AuditProbationJobs))
	}
	if m.AuditResolveTimeout != 0 {
		n += 2 + sovParams(uint64(m.AuditResolveTimeout))
	}
	if m.SilenceSlashBps != 0 {
		n += 2 + sovParams(uint64(m.SilenceSlashBps))
	}
	if m.AppealWindow != 0 {
		n += 2 + sovParams(uint64(m.AppealWindow))
	}
	if m.AuditMinQuorum != 0 {
		n += 2 + sovParams(uint64(m.AuditMinQuorum))
	}
	if m.HoldBps != 0 {
		n += 2 + sovParams(uint64(m.HoldBps))
	}
	if m.CommitteeMinVrfContributors != 0 {
		n += 2 + sovParams(uint64(m.CommitteeMinVrfContributors))
	}
	if m.AvailThresholdBps != 0 {
		n += 2 + sovParams(uint64(m.AvailThresholdBps))
	}
	if m.AvailDeadlineBlocks != 0 {
		n += 2 + sovParams(uint64(m.AvailDeadlineBlocks))
	}
	if m.AvailSlashBps != 0 {
		n += 2 + sovParams(uint64(m.AvailSlashBps))
	}
	if m.AvailSlashMax != 0 {
		n += 2 + sovParams(uint64(m.AvailSlashMax))
	}
	if m.AvailFailWindow != 0 {
		n += 2 + sovParams(uint64(m.AvailFailWindow))
	}
	if m.AvailFailK != 0 {
		n += 2 + sovParams(uint64(m.AvailFailK))
	}
	if m.JurorFreshnessBlocks != 0 {
		n += 2 + sovParams(uint64(m.JurorFreshnessBlocks))
	}
	if m.MinerPruneBlocks != 0 {
		n += 2 + sovParams(uint64(m.MinerPruneBlocks))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinStake", wireType)
			}
			m.MinStake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinStake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolFeeBps", wireType)
			}
			m.ProtocolFeeBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProtocolFeeBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorRewardBps", wireType)
			}
			m.ValidatorRewardBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorRewardBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TeamFeeBps", wireType)
			}
			m.TeamFeeBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TeamFeeBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinerVestBps", wireType)
			}
			m.MinerVestBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinerVestBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashLeakBps", wireType)
			}
			m.SlashLeakBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlashLeakBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochBlocks", wireType)
			}
			m.EpochBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkGateBps", wireType)
			}
			m.WorkGateBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WorkGateBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeBurnBps", wireType)
			}
			m.FeeBurnBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeBurnBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnforceModelRegistry", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnforceModelRegistry = bool(v != 0)
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitteeRevealDelay", wireType)
			}
			m.CommitteeRevealDelay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitteeRevealDelay |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailEpochBlocks", wireType)
			}
			m.AvailEpochBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvailEpochBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailPayoutBps", wireType)
			}
			m.AvailPayoutBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvailPayoutBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailRequireDemand", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AvailRequireDemand = bool(v != 0)
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VrfBeaconPubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VrfBeaconPubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitteeSeedSource", wireType)
			}
			m.CommitteeSeedSource = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitteeSeedSource |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeWindow", wireType)
			}
			m.DisputeWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DisputeWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeBond", wireType)
			}
			m.DisputeBond = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DisputeBond |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 23:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationMode", wireType)
			}
			m.VerificationMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerificationMode |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 24:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditSampleBps", wireType)
			}
			m.AuditSampleBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuditSampleBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 25:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditAdaptive", wireType)
			}
			m.AuditAdaptive = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuditAdaptive |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 26:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditProbationJobs", wireType)
			}
			m.AuditProbationJobs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuditProbationJobs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 27:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditResolveTimeout", wireType)
			}
			m.AuditResolveTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuditResolveTimeout |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 28:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SilenceSlashBps", wireType)
			}
			m.SilenceSlashBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SilenceSlashBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 29:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppealWindow", wireType)
			}
			m.AppealWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppealWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 30:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditMinQuorum", wireType)
			}
			m.AuditMinQuorum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuditMinQuorum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 31:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HoldBps", wireType)
			}
			m.HoldBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HoldBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 32:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitteeMinVrfContributors", wireType)
			}
			m.CommitteeMinVrfContributors = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitteeMinVrfContributors |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 33:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailThresholdBps", wireType)
			}
			m.AvailThresholdBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvailThresholdBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 34:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailDeadlineBlocks", wireType)
			}
			m.AvailDeadlineBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvailDeadlineBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 35:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailSlashBps", wireType)
			}
			m.AvailSlashBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvailSlashBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 36:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailSlashMax", wireType)
			}
			m.AvailSlashMax = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvailSlashMax |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 37:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailFailWindow", wireType)
			}
			m.AvailFailWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvailFailWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 38:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailFailK", wireType)
			}
			m.AvailFailK = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvailFailK |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 39:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JurorFreshnessBlocks", wireType)
			}
			m.JurorFreshnessBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JurorFreshnessBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 40:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinerPruneBlocks", wireType)
			}
			m.MinerPruneBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinerPruneBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
