"""The miner's Cosmos keyring: which backend, which passphrase, and how `dendrad` is handed it.

THE BACKEND IS READ FROM THE STATE OF THE DISK, NEVER FROM A SETTING.
    keyring-test holds keys, keyring-file holds nothing   -> `test`, with a warning: the key is in clear
    keyring-file holds anything                           -> `file`, and the passphrase is REQUIRED
    both hold something                                   -> REFUSED: two keyrings are two possible
                                                             identities, and guessing picks one
    neither holds anything                                -> `file` when the passphrase FILE is there,
                                                             `test` otherwise, with the same warning
A setting could say `file` over a keyring that is `test` (or the reverse): `dendrad` would then look in a
directory that holds no key, the miner would find "no key", and create a NEW one -- a new address, a new
identity, an unfunded account, while the stake stays on chain under the old one. The disk cannot
disagree with itself.

WHERE THE PASSPHRASE COMES FROM. A file mounted READ-ONLY into the container
(`/run/dendra-secrets/keyring-passphrase`, `deploy/testnet-miner/docker-compose.yml`), generated by the kit
outside the miner-keys volume and outside the clone. Never argv (`ps` and `/proc/<pid>/cmdline` are
readable by every local process) and never an environment variable the kit hands the container
(`docker inspect` prints it). `DENDRA_MINER_PASSPHRASE` is still read OUTSIDE the container, as a
fallback, with a warning that says what it exposes.
It reaches `dendrad` on STDIN, one line per prompt. `dendrad keys add` on a keyring that has no passphrase
yet reads it twice (enter, re-enter), every other command once; a command never reads past what it asks
for, so every call is handed STDIN_COPIES lines.

WHAT IT PROTECTS, AND WHAT IT DOES NOT. An encrypted keyring protects the miner-keys volume and every
backup of it: a copy of the volume alone no longer holds a usable key. It does not protect a host that is
compromised while the miner runs: the passphrase sits next to the volume, on the same host, by design --
the miner restarts unattended.

THE ZERO RULE, ON A KEY. `dendrad` answers a wrong or missing passphrase with "<name> is not a valid name
or address: too many failed passphrase attempts", which reads like an absent key; and `dendrad keys list`
answers it with exit 0 and an EMPTY list. Taking either at its word, a miner that cannot open its keyring
would conclude it has no key and create one. So a key is ABSENT only when dendrad says so AND the disk
agrees (no `<name>.info` in the keyring directory); anything else is UNREADABLE, and nothing is created.

    python3 -m modea.keyring list                         every key, as `dendrad keys list --output json`
    python3 -m modea.keyring status <keydir>              keyring, recovery phrase, payout record (JSON)
    python3 -m modea.keyring recovery <file>              the kept recovery phrase, opened (JSON)
    python3 -m modea.keyring forget-recovery <file> --address A --yes   removes it; nothing without --yes
    python3 -m modea.keyring vrf-pubkey <file>            public key of a (possibly encrypted) VRF secret
    python3 -m modea.keyring plan <keydir> [--app-settings -]   what encrypt-keys.sh reads (key=value)
    python3 -m modea.keyring migrate <keydir> --yes       test -> file, same addresses verified
    python3 -m modea.keyring address <keydir>             identity, address and keys at rest (key=value)

THE ADDRESS IS READ HERE, NEVER IN THE LOGS. The daemon prints it once, at start ("ready  addr=..."), and the
kit ROTATES the container logs (deploy/testnet-miner/docker-compose.yml, `logging:`): a line printed once is
gone after enough traffic. `address` reads it from the keyring itself, running or stopped:
    docker compose -p dendra-miner exec -T miner python3 -m modea.keyring address /data/keys          (running)
    docker compose -p dendra-miner run --rm --no-deps -T --entrypoint python3 miner -m modea.keyring address /data/keys
"""
from __future__ import annotations

import argparse
import json
import os
import re
import secrets
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field

PASSPHRASE_FILE = "/run/dendra-secrets/keyring-passphrase"
PASSPHRASE_FILE_ENV = "DENDRA_KEYRING_PASSPHRASE_FILE"     # a PATH, never the secret itself
ENV_PASSPHRASE = "DENDRA_MINER_PASSPHRASE"
TEST, FILE = "test", "file"
DIRS = {TEST: "keyring-test", FILE: "keyring-file"}
STDIN_COPIES = 2
MIN_LENGTH = 8                     # dendrad's own floor (client/input: "password must be at least 8 characters")
RECOVERY_NAME = "recovery-phrase.json"
PAYOUT_RECORD = "payout-declared.json"
PRESENT, ABSENT, UNREADABLE, NOT_RUN = "present", "absent", "unreadable", "not run"
_ADDRESS = re.compile(r"dendra1[0-9a-z]+")      # what `keys show -a` prints on success; its checksum is dendrad's
# The armor `keys export` prints opens with five dashes and BEGIN, and closes with five dashes and END. The
# markers are composed, not written whole: the opening of a private-key block is refused by the publication's
# secret scan wherever it appears, a source file included.
_ARMOR_DASHES = "-" * 5
ARMOR_BEGIN, ARMOR_END = _ARMOR_DASHES + "BEGIN", _ARMOR_DASHES + "END"
SECRETS_HINT = ("the kit mounts the directory named by DENDRA_SECRETS_DIR (deploy/testnet-miner/.env) "
                "read-only at /run/dendra-secrets; deploy/join.sh writes that line and creates the file "
                "keyring-passphrase in it")


class KeyringError(RuntimeError):
    """A keyring this process cannot use. `cause` names it in a few words, `hint` says what to do."""
    cause = "keyring error"
    hint = ""

    def __init__(self, why: str):
        super().__init__(why)
        self.why = why

    def __str__(self) -> str:
        return f"{self.cause}: {self.why}"


class KeyringAmbiguous(KeyringError):
    cause = "two keyrings"
    hint = ("keyring-test and keyring-file both hold keys: keep the one that holds this miner's address, "
            "move the other one out of the volume, then start again")


class PassphraseMissing(KeyringError):
    cause = "passphrase missing"
    hint = "the keyring is encrypted and no passphrase was found: " + SECRETS_HINT


class PassphraseUnreadable(KeyringError):
    cause = "passphrase unreadable"
    hint = "the passphrase file exists and cannot be used: " + SECRETS_HINT


class PassphraseConflict(KeyringError):
    cause = "two passphrases"
    hint = (f"the passphrase file and {ENV_PASSPHRASE} disagree: unset {ENV_PASSPHRASE} (the kit reads the "
            "file) or make them equal")


class PassphraseRejected(KeyringError):
    cause = "passphrase missing or wrong"
    hint = ("the passphrase given is not the one this keyring was encrypted with: restore the right "
            "keyring-passphrase file from your backup; without it, the 24-word recovery phrase rebuilds the "
            "key (dendrad keys add <name> --recover)")


class KeyringUnreadable(KeyringError):
    cause = "keyring unreadable"
    hint = "nothing was created: a key this process cannot read is never replaced by a new one"


class RecoveryPending(KeyringError):
    """A key would be created while the recovery phrase of an EARLIER key is still kept, never confirmed as
    written down. The file has one name: a creation would replace it, and with it the only copy of the
    words of a key that may still hold the stake."""
    cause = "an earlier recovery phrase not written down"
    hint = ("nothing was created. From deploy/testnet-miner, show the kept words: docker compose run --rm "
            "--no-deps -T --entrypoint python3 miner -m modea.keyring recovery /data/keys/" + RECOVERY_NAME
            + " ; write them down, then remove the file with the same command, `forget-recovery /data/keys/"
            + RECOVERY_NAME + " --address <its address> --yes` in place of `recovery ...` (the Dendra "
            "application does both while the miner runs), and start the miner again")


# ── the disk ─────────────────────────────────────────────────────────────────────────────────────────
def default_dir(env=None) -> str:
    """The keyring directory dendrad would use: DENDRA_KEYRING_DIR, else DENDRA_HOME, else ~/.dendra.
    Read at CALL time: a module that read it at import would keep a directory the caller changed since."""
    env = os.environ if env is None else env
    d = (env.get("DENDRA_KEYRING_DIR") or "").strip() or (env.get("DENDRA_HOME") or "").strip()
    return d or os.path.join(os.path.expanduser("~"), ".dendra")


def _files(path: str) -> list:
    """Regular files in `path`; [] when it does not exist. A directory that exists and cannot be listed
    RAISES: an unlisted keyring is not an empty one."""
    try:
        names = os.listdir(path)
    except FileNotFoundError:
        return []
    except NotADirectoryError as e:
        raise KeyringUnreadable(f"{path} is not a directory") from e
    except OSError as e:
        raise KeyringUnreadable(f"{path} cannot be listed ({type(e).__name__}: {e})") from e
    return sorted(n for n in names if os.path.isfile(os.path.join(path, n)))


def _holds(directory: str, backend: str) -> list:
    keep = (".info", ".address") if backend == TEST else (".info", ".address", "keyhash")
    return [n for n in _files(os.path.join(directory, DIRS[backend])) if n.endswith(keep)]


def disk_state(directory: str) -> str:
    """'test' | 'file' | 'both' | 'none'. A directory that exists but is EMPTY counts as absent:
    `dendrad keys list` creates keyring-test/ or keyring-file/ on an empty keyring dir (measured)."""
    t, f = bool(_holds(directory, TEST)), bool(_holds(directory, FILE))
    return "both" if t and f else (FILE if f else (TEST if t else "none"))


def key_names(directory: str, backend: str) -> list:
    """Names of the keys a backend directory holds, from its `<name>.info` files."""
    return sorted(n[:-len(".info")] for n in _holds(directory, backend) if n.endswith(".info"))


# ── the passphrase ───────────────────────────────────────────────────────────────────────────────────
@dataclass
class Passphrase:
    value: str | None
    source: str                    # "file" | "env" | "none"
    path: str
    warnings: list = field(default_factory=list)


def passphrase_path(env=None) -> str:
    env = os.environ if env is None else env
    return (env.get(PASSPHRASE_FILE_ENV) or "").strip() or PASSPHRASE_FILE


def read_passphrase(env=None) -> Passphrase:
    """The passphrase from its file, else from DENDRA_MINER_PASSPHRASE (with a warning), else none.
    A file that EXISTS and cannot be used raises: it is a passphrase that was meant to be there, and
    reading it as "none" would choose the clear keyring for a new key."""
    env = os.environ if env is None else env
    path = passphrase_path(env)
    from_env = env.get(ENV_PASSPHRASE, "")
    try:
        with open(path, "rb") as f:
            raw = f.read(4097)
    except FileNotFoundError:
        raw = None
    except IsADirectoryError as e:
        raise PassphraseUnreadable(f"{path} is a directory, not a passphrase file") from e
    except OSError as e:
        raise PassphraseUnreadable(f"{path} exists but cannot be read ({type(e).__name__}: {e})") from e
    if raw is not None:
        if len(raw) > 4096:
            raise PassphraseUnreadable(f"{path} is longer than 4096 bytes: not a passphrase file")
        try:
            value = raw.decode("utf-8").rstrip("\r\n")
        except UnicodeDecodeError as e:
            raise PassphraseUnreadable(f"{path} is not UTF-8 text") from e
        if not value:
            raise PassphraseUnreadable(f"{path} is empty")
        if "\n" in value or "\r" in value:
            raise PassphraseUnreadable(f"{path} holds more than one line; dendrad reads one line per prompt")
        if from_env and from_env != value:
            raise PassphraseConflict(f"{path} and {ENV_PASSPHRASE} hold different passphrases")
        return Passphrase(value, "file", path)
    if from_env:
        return Passphrase(from_env, "env", path, [
            f"the passphrase comes from {ENV_PASSPHRASE}: an environment variable is readable by "
            f"'docker inspect' and in /proc/<pid>/environ. The kit reads it from a file instead ({path})."])
    return Passphrase(None, "none", path)


# ── the keyring ──────────────────────────────────────────────────────────────────────────────────────
@dataclass
class Keyring:
    backend: str
    directory: str
    passphrase: str | None
    source: str
    state: str
    passphrase_file: str
    warnings: list = field(default_factory=list)

    def flags(self) -> list:
        """The keyring flags every dendrad call that reads a key carries. The directory is ALWAYS named:
        the backend was chosen by looking at it, and dendrad must look at the same one."""
        return ["--keyring-backend", self.backend, "--keyring-dir", self.directory]

    def stdin(self) -> str:
        """What the call is handed on stdin: the passphrase once per prompt for `file`, nothing for `test`
        (an empty, closed stdin: a prompt nobody answers fails at once instead of waiting)."""
        if self.backend != FILE or not self.passphrase:
            return ""
        return "".join(self.passphrase + "\n" for _ in range(STDIN_COPIES))

    @property
    def seal_with(self) -> str:
        """The passphrase the key FILES (.sk, .vrf, .attestkey, the recovery phrase) are written under:
        the keyring's, in `file` mode; under `test`, only one given explicitly by DENDRA_MINER_PASSPHRASE
        (its historical meaning). A passphrase file next to a `test` keyring does not seal them: the
        migration (encrypt-keys.sh) does, once the keyring itself is encrypted."""
        if self.backend == FILE or self.source == "env":
            return self.passphrase or ""
        return ""

    @property
    def open_with(self) -> str:
        """The passphrase a key file written under it is opened with: whatever passphrase is available."""
        return self.passphrase or ""


def resolve(directory: str | None = None, env=None) -> Keyring:
    """The keyring to use, decided from the disk. Raises a KeyringError subclass that names the cause."""
    env = os.environ if env is None else env
    d = directory or default_dir(env)
    state = disk_state(d)
    if state == "both":
        raise KeyringAmbiguous(f"{os.path.join(d, DIRS[TEST])} and {os.path.join(d, DIRS[FILE])} both hold keys")
    pp = read_passphrase(env)
    warnings = list(pp.warnings)
    if state == FILE or (state == "none" and pp.source == "file"):
        if not pp.value:
            raise PassphraseMissing(f"{os.path.join(d, DIRS[FILE])} is encrypted and {pp.path} does not exist"
                                    + (f" (nor is {ENV_PASSPHRASE} set)" if state == FILE else ""))
        if len(pp.value) < MIN_LENGTH:
            raise PassphraseUnreadable(f"the passphrase is shorter than the {MIN_LENGTH} characters dendrad requires")
        return Keyring(FILE, d, pp.value, pp.source, state, pp.path, warnings)
    clear = (f"the miner's keyring is the TEST keyring ({os.path.join(d, DIRS[TEST])}): its key is stored IN "
             f"CLEAR, in the miner-keys volume and in every backup of it.")
    if state == TEST and pp.source == "file":
        clear += " A passphrase is available: bash deploy/testnet-miner/encrypt-keys.sh encrypts the existing key."
    elif state == "none":
        clear += f" No passphrase file at {pp.path}, so a new key is created in clear."
    warnings.append(clear)
    return Keyring(TEST, d, pp.value, pp.source, state, pp.path, warnings)


def run(kr: Keyring, argv: list, timeout: float = 120, before: str = "") -> tuple:
    """(rc, stdout, stderr) of a dendrad call that reads the keyring; rc None when it could not run.
    `argv` already carries kr.flags(); `before` goes on stdin ahead of the passphrase lines (the
    passphrase of an exported key, for `keys import`)."""
    try:
        p = subprocess.run(argv, capture_output=True, text=True, timeout=timeout, input=before + kr.stdin())
    except (OSError, subprocess.TimeoutExpired) as e:
        return None, "", f"{type(e).__name__}: {e}"
    return p.returncode, p.stdout or "", p.stderr or ""


def explain(text: str) -> str:
    """The keyring refusal a dendrad output carries, in words; '' when it carries none."""
    t = text or ""
    if "password must be at least" in t:
        return f"the keyring passphrase is shorter than the {MIN_LENGTH} characters dendrad requires"
    if "too many failed passphrase attempts" in t or "incorrect passphrase" in t:
        return ("the keyring passphrase is missing or wrong (dendrad says 'too many failed passphrase "
                "attempts', and prints it as 'not a valid name or address': the key is there, the "
                "passphrase does not open it)")
    return ""


def last_line(text: str) -> str:
    lines = [ln.strip() for ln in (text or "").splitlines() if ln.strip()]
    keep = [ln for ln in lines if not ln.startswith(("Usage:", "Flags:", "Global Flags:", "-", "dendrad "))]
    return (keep or lines or [""])[-1][:300]


def key_state(kr: Keyring, name: str, dendrad: str = "dendrad") -> tuple:
    """(PRESENT, address) | (ABSENT, why) | (UNREADABLE, why) | (NOT_RUN, why).
    ABSENT needs TWO readings that agree: dendrad's "not a valid name or address" without a passphrase
    refusal, and no `<name>.info` on the disk. Only that state may lead to creating a key."""
    rc, out, err = run(kr, [dendrad, "keys", "show", name, "-a", *kr.flags()], timeout=60)
    m = _ADDRESS.search(out or "")
    if rc == 0 and m:
        return PRESENT, m.group(0)
    if rc is None:
        return NOT_RUN, f"dendrad could not be run: {err}"
    text = (out or "") + "\n" + (err or "")
    cause = explain(text)
    if cause:
        return UNREADABLE, cause
    try:
        on_disk = name in key_names(kr.directory, kr.backend)
    except KeyringUnreadable as e:
        return UNREADABLE, str(e)
    where = os.path.join(kr.directory, DIRS[kr.backend])
    if on_disk:
        return UNREADABLE, f"{name}.info is in {where} and dendrad does not read it: {last_line(text)}"
    if "not a valid name or address" in text or "key not found" in text:
        return ABSENT, f"no key named {name} in {where}"
    return UNREADABLE, f"dendrad keys show {name} exited {rc}: {last_line(text)}"


def create_key(kr: Keyring, name: str, dendrad: str = "dendrad") -> tuple:
    """(rc, stdout, stderr) of `dendrad keys add <name> --output json`. dendrad refuses (rc 1, 'aborted')
    to replace an existing name when nobody answers its confirmation: a creation never overwrites."""
    return run(kr, [dendrad, "keys", "add", name, *kr.flags(), "--output", "json"])


def list_keys(kr: Keyring, dendrad: str = "dendrad") -> list:
    """Every key, read by dendrad and CONFRONTED with the disk. dendrad answers a wrong passphrase on
    `keys list` with exit 0 and an empty list (measured): an answer that misses a key the disk holds is
    a failed read, never "no key"."""
    on_disk = key_names(kr.directory, kr.backend)
    rc, out, err = run(kr, [dendrad, "keys", "list", *kr.flags(), "--output", "json"], timeout=60)
    cause = explain((out or "") + "\n" + (err or ""))
    if cause:
        raise PassphraseRejected(cause)
    if rc is None or rc != 0:
        raise KeyringUnreadable(f"dendrad keys list exited {rc}: {last_line((out or '') + chr(10) + (err or ''))}")
    i = (out or "").find("[")
    try:
        keys = json.loads(out[i:]) if i >= 0 else None
    except ValueError:
        keys = None
    if not isinstance(keys, list) or not all(isinstance(k, dict) for k in keys):
        raise KeyringUnreadable("dendrad keys list did not answer a JSON list")
    missing = sorted(set(on_disk) - {str(k.get("name", "")) for k in keys})
    if missing:
        raise KeyringUnreadable(f"the keyring holds {len(on_disk)} key(s) and dendrad read {len(keys)}: "
                                f"{', '.join(missing)} not read")
    return keys


# ── the files sealed with the keyring's passphrase ─────────────────────────────────────────────────
def read_recovery(path: str, passphrase: str) -> dict:
    """The kept recovery phrase, opened. Raises FileNotFoundError, crypto.KeyEnvelopeError, ValueError."""
    from . import crypto
    raw, _ = crypto.read_envelope(path, passphrase, crypto.AAD_RECOVERY)
    d = json.loads(raw.decode("utf-8"))
    if not isinstance(d, dict):
        raise ValueError("not a JSON object")
    return d


def recovery_head(path: str, passphrase: str) -> dict:
    """Whose phrase is kept, without the words: {"present", "address", "words", "sealed"} or, when the
    file exists and cannot be opened, {"present": None, "error"}."""
    from . import crypto
    try:
        with open(path, "rb") as f:
            sealed = crypto.is_sealed(f.read(len(crypto.MAGIC)))
        d = read_recovery(path, passphrase)
    except FileNotFoundError:
        return {"present": False}
    except (OSError, ValueError, crypto.KeyEnvelopeError) as e:
        return {"present": None, "error": f"{type(e).__name__}: {e}"}
    n = len(str(d.get("mnemonic") or "").split())
    return {"present": n in (12, 24), "address": str(d.get("address") or ""), "words": n, "sealed": sealed}


def key_files(keydir: str, mid: str) -> dict:
    """{name: "sealed" | "clear" | "absent" | "unread"} for the miner's key files."""
    from . import crypto
    out = {}
    for n in (f"{mid}.sk", f"{mid}.vrf", f"{mid}.attestkey", RECOVERY_NAME):
        try:
            with open(os.path.join(keydir, n), "rb") as f:
                out[n] = "sealed" if crypto.is_sealed(f.read(len(crypto.MAGIC))) else "clear"
        except FileNotFoundError:
            out[n] = "absent"
        except OSError:
            out[n] = "unread"
    return out


def payout_record(keydir: str) -> dict | None:
    """The last payout declaration the programme ACCEPTED for this volume, or None."""
    try:
        with open(os.path.join(keydir, PAYOUT_RECORD), encoding="utf-8") as f:
            d = json.load(f)
    except (OSError, ValueError):
        return None
    return d if isinstance(d, dict) else None


def resolved_identity(keydir: str) -> str:
    try:
        with open(os.path.join(keydir, "identite-resolue"), encoding="utf-8") as f:
            v = "".join(f.read().split())
    except OSError:
        return ""
    return v if v.startswith("dm1") else ""


def seal_files(keydir: str, mid: str, passphrase: str) -> dict:
    """Re-encrypts, atomically, every key file of `mid` still in clear. {name: state after}."""
    from . import crypto
    aad = {f"{mid}.sk": crypto.AAD_SK, f"{mid}.vrf": crypto.AAD_VRF, f"{mid}.attestkey": crypto.AAD_ATTEST,
           RECOVERY_NAME: crypto.AAD_RECOVERY}
    for n, a in aad.items():
        p = os.path.join(keydir, n)
        if os.path.exists(p):
            crypto.load_secret(p, passphrase, a, seal_with=passphrase)
    return key_files(keydir, mid)


# ── the migration (deploy/testnet-miner/encrypt-keys.sh) ─────────────────────────────────────────────
def _kv(k: str, v) -> None:
    print(k + "=" + " ".join(str(v).split()), flush=True)


def _keyring_dir_for(keydir: str, env=None) -> str:
    env = os.environ if env is None else env
    return (env.get("DENDRA_KEYRING_DIR") or "").strip() or os.path.join(keydir, "cosmos")


def plan(keydir: str, app_settings: str | None, env=None) -> int:
    """What encrypt-keys.sh needs to decide, as key=value lines. Writes nothing."""
    env = os.environ if env is None else env
    d = _keyring_dir_for(keydir, env)
    try:
        state = disk_state(d)
    except KeyringError as e:
        _kv("state", "unread")
        _kv("why", str(e))
        return 0
    _kv("state", state)
    _kv("keyring_dir", d)
    if state in (TEST, FILE):
        names = key_names(d, state)
        _kv("keys", len(names))
        _kv("names", ",".join(names))
    mid = resolved_identity(keydir)
    _kv("id", mid)
    st, val = None, ""
    if state in (TEST, FILE) and mid:
        try:
            kr = resolve(d, env) if state == FILE else Keyring(TEST, d, None, "none", state, "")
            st, val = key_state(kr, mid)
        except KeyringError as e:
            st, val = UNREADABLE, str(e)
        _kv("address", val if st == PRESENT else "")
        if st != PRESENT:
            _kv("why", val)
    # AN ENCRYPTED KEYRING IS "ALREADY DONE" ONLY WHEN IT OPENS. A `file` keyring whose passphrase is missing
    # or wrong is the state in which the miner stops (exit 4): reading it as "nothing to do" would answer the
    # one case encrypt-keys.sh exists for with a green. `opens` is yes only on a positive reading: the
    # identity's key read back under the passphrase, or -- with no identity resolved yet -- every key the
    # disk holds read by dendrad. Anything else is no, with its reason in `why`.
    if state == FILE:
        if mid:
            opened = st == PRESENT
        else:
            try:
                list_keys(resolve(d, env))
                opened = True
            except KeyringError as e:
                opened = False
                _kv("why", str(e))
        _kv("opens", "yes" if opened else "no")
    try:
        pp = read_passphrase(env)
        _kv("passphrase", pp.source)
    except KeyringError as e:
        _kv("passphrase", "unread")
        _kv("why", str(e))
    head = recovery_head(os.path.join(keydir, RECOVERY_NAME), "")
    _kv("recovery", {True: "present", False: "absent"}.get(head.get("present"), "unread"))
    _kv("recovery_address", head.get("address", ""))
    # The application keeps the LAST address whose words were typed back, and -- one identity per card, so
    # several phrases on one machine -- the list of every such address. This identity's address is reported
    # as confirmed when either names it; otherwise the last one is reported as it always was, and the caller
    # compares it with this identity's address.
    confirmed = ""
    if app_settings:
        try:
            s = json.loads(app_settings)
        except ValueError:
            s = None
        if isinstance(s, dict):
            confirmed = str(s.get("recovery_confirmed_address") or "")
            many = s.get("recovery_confirmed_addresses")
            mine = val if st == PRESENT else ""
            if mine and isinstance(many, list) and mine in [str(x) for x in many]:
                confirmed = mine
    _kv("confirmed_address", confirmed)
    return 0


def migrate(keydir: str, env=None, dendrad: str = "dendrad") -> int:
    """test -> file, in place. Every key is exported from keyring-test and imported into keyring-file
    under the passphrase; keyring-test is removed only once EVERY key reads back, from keyring-file, with
    the address it had. On any failure before that, keyring-file is removed and keyring-test is left as
    it was. Then the key files are sealed. Prints key=value lines; 0 done, 1 failed, 2 refused."""
    env = os.environ if env is None else env
    d = _keyring_dir_for(keydir, env)
    try:
        state = disk_state(d)
        pp = read_passphrase(env)
    except KeyringError as e:
        _kv("result", "refused")
        _kv("why", str(e))
        return 2
    if state != TEST:
        _kv("result", "refused")
        _kv("why", f"the keyring state is '{state}', not 'test': nothing to migrate")
        return 2
    if pp.source != "file" or not pp.value or len(pp.value) < MIN_LENGTH:
        _kv("result", "refused")
        _kv("why", f"no usable passphrase file at {pp.path}")
        return 2
    src = Keyring(TEST, d, None, "none", TEST, "")
    dst = Keyring(FILE, d, pp.value, "file", "none", pp.path)
    names = key_names(d, TEST)
    expected = {}
    for n in names:
        st, val = key_state(src, n, dendrad)
        if st != PRESENT:
            _kv("result", "failed")
            _kv("why", f"{n} does not read in the test keyring: {val}")
            return 1
        expected[n] = val
    work = tempfile.mkdtemp(prefix="dendra-migrate-")
    os.chmod(work, 0o700)
    ok = False
    try:
        for n in names:
            exp_pass = secrets.token_urlsafe(24)
            rc, out, err = run(src, [dendrad, "keys", "export", n, *src.flags()], before=exp_pass + "\n")
            armor = (out or "") + (err or "")
            i, j = armor.find(ARMOR_BEGIN), armor.rfind(ARMOR_END)
            if rc != 0 or i < 0 or j < 0:
                raise RuntimeError(f"export of {n} failed: {last_line(err or out)}")
            j = armor.find("\n", j)
            path = os.path.join(work, n + ".armor")
            fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                f.write(armor[i:(j if j > 0 else len(armor))].rstrip() + "\n")
            rc, out, err = run(dst, [dendrad, "keys", "import", n, path, *dst.flags()], before=exp_pass + "\n")
            os.remove(path)
            if rc != 0:
                raise RuntimeError(f"import of {n} failed: {explain(err) or last_line(err or out)}")
        for n in names:
            st, val = key_state(dst, n, dendrad)
            if st != PRESENT or val != expected[n]:
                raise RuntimeError(f"{n} reads back from keyring-file as {val!r}, expected {expected[n]}")
            _kv("verified", f"{n} {val}")
        ok = True
    except Exception as e:  # noqa: BLE001 -- every failure rolls back the same way
        _kv("result", "failed")
        _kv("why", f"{type(e).__name__}: {e}")
    finally:
        shutil.rmtree(work, ignore_errors=True)
    if not ok:
        shutil.rmtree(os.path.join(d, DIRS[FILE]), ignore_errors=True)
        _kv("rolled_back", "keyring-file removed, keyring-test left as it was")
        return 1
    shutil.rmtree(os.path.join(d, DIRS[TEST]))
    _kv("removed", DIRS[TEST])
    mid = resolved_identity(keydir)
    if mid:
        for n, st in seal_files(keydir, mid, pp.value).items():
            _kv("file", f"{n} {st}")
    _kv("result", "migrated")
    _kv("keys", len(names))
    return 0


AT_REST = {TEST: "clear", FILE: "encrypted", "none": "none", "both": "both"}


def address_report(keydir: str, env=None) -> int:
    """identity=, address=, at_rest=, why= -- what the volume holds, read from the keyring, never from a log.
    at_rest is the state of the DISK (clear | encrypted | none | both | unread), not of a setting: a kit whose
    .env names a passphrase while its existing keyring is still `test` holds its keys IN CLEAR, and says so.
    Exit 0 when the address was read; 3 when it was not (the reason in why=), never an empty success."""
    env = os.environ if env is None else env
    d = _keyring_dir_for(keydir, env)
    mid = resolved_identity(keydir)
    try:
        state = disk_state(d)
    except KeyringError as e:
        _kv("identity", mid)
        _kv("address", "")
        _kv("at_rest", "unread")
        _kv("why", str(e))
        return 3
    _kv("identity", mid)
    _kv("at_rest", AT_REST[state])
    if not mid:
        _kv("address", "")
        _kv("why", "no identity resolved yet in " + keydir + " (the daemon writes identite-resolue at its first start)")
        return 3
    try:
        st, val = key_state(resolve(d, env), mid)
    except KeyringError as e:
        st, val = UNREADABLE, f"{e}" + (f" -- {e.hint}" if e.hint else "")
    _kv("address", val if st == PRESENT else "")
    _kv("why", "" if st == PRESENT else val)
    return 0 if st == PRESENT else 3


# ── command line ─────────────────────────────────────────────────────────────────────────────────────
def _fail(e: Exception, code: int = 1) -> int:
    hint = getattr(e, "hint", "")
    print(f"keyring: {e}" + (f" -- {hint}" if hint else ""), file=sys.stderr)
    return code


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="python3 -m modea.keyring")
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("list")
    s = sub.add_parser("status")
    s.add_argument("keydir")
    r = sub.add_parser("recovery")
    r.add_argument("file")
    fr = sub.add_parser("forget-recovery")
    fr.add_argument("file")
    fr.add_argument("--address", required=True)
    fr.add_argument("--yes", action="store_true")
    v = sub.add_parser("vrf-pubkey")
    v.add_argument("file")
    p = sub.add_parser("plan")
    p.add_argument("keydir")
    p.add_argument("--app-settings", default=None, help="'-' reads the application's app.json on stdin")
    m = sub.add_parser("migrate")
    m.add_argument("keydir")
    m.add_argument("--yes", action="store_true")
    ad = sub.add_parser("address")
    ad.add_argument("keydir")
    a = ap.parse_args(argv)

    if a.cmd == "list":
        try:
            kr = resolve()
            print(json.dumps(list_keys(kr)))
        except KeyringError as e:
            return _fail(e)
        return 0
    if a.cmd == "status":
        d = _keyring_dir_for(a.keydir)
        out = {"keyring": {"dir": d}}
        passphrase = ""
        try:
            kr = resolve(d)
            passphrase = kr.open_with
            out["keyring"].update(state=kr.state, backend=kr.backend, passphrase=kr.source, error="")
        except KeyringError as e:
            out["keyring"].update(state=None, backend=None, passphrase=None, error=str(e))
        mid = resolved_identity(a.keydir)
        out["identity"] = mid
        out["recovery"] = recovery_head(os.path.join(a.keydir, RECOVERY_NAME), passphrase)
        out["files"] = key_files(a.keydir, mid) if mid else {}
        out["payout"] = payout_record(a.keydir)
        print(json.dumps(out))
        return 0
    if a.cmd in ("recovery", "forget-recovery"):
        from . import crypto
        try:
            pp = read_passphrase()
            d = read_recovery(a.file, pp.value or "")
        except FileNotFoundError:
            print(json.dumps({"present": False}))
            return 3
        except (KeyringError, crypto.KeyEnvelopeError, OSError, ValueError) as e:
            return _fail(e)
        if a.cmd == "recovery":
            print(json.dumps({"address": str(d.get("address") or ""), "name": str(d.get("name") or ""),
                              "mnemonic": str(d.get("mnemonic") or "")}))
            return 0
        if str(d.get("address") or "") != a.address or not a.address:
            print(json.dumps({"removed": False, "why": "the phrase on the volume is not the one confirmed"}))
            return 2
        # REMOVING IT IS IRREVERSIBLE, AND THE ADDRESS ABOVE PROVES NOTHING: it is public. Like `migrate`, this
        # changes nothing without --yes; the application passes it once three of the words were typed back.
        if not a.yes:
            print(json.dumps({"removed": False, "why": "forget-recovery deletes the only kept copy of the words: "
                                                        "--yes is required, once they are written down"}))
            return 2
        os.remove(a.file)
        print(json.dumps({"removed": not os.path.exists(a.file)}))
        return 0 if not os.path.exists(a.file) else 1
    if a.cmd == "vrf-pubkey":
        from . import crypto
        try:
            pp = read_passphrase()
            sk = crypto.load_secret(a.file, pp.value or "", crypto.AAD_VRF).decode().strip()
        except (KeyringError, crypto.KeyEnvelopeError, OSError) as e:
            return _fail(e)
        vrf = shutil.which("dendra-vrf") or "dendra-vrf"
        # The secret goes through the environment, never argv: /proc/<pid>/cmdline is world-readable.
        r = subprocess.run([vrf, "pubkey"], capture_output=True, text=True, timeout=10,
                           env={**os.environ, "DENDRA_VRF_SK": sk})
        print(r.stdout.strip())
        return r.returncode
    if a.cmd == "plan":
        settings = sys.stdin.read() if a.app_settings == "-" else None
        return plan(a.keydir, settings)
    if a.cmd == "address":
        return address_report(a.keydir)
    if a.cmd == "migrate":
        if not a.yes:
            _kv("result", "refused")
            _kv("why", "migrate changes the keyring: --yes is required")
            return 2
        return migrate(a.keydir)
    return 2


if __name__ == "__main__":
    sys.exit(main())
