// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dendra/emission/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the emission module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// EMISSION ENGINE STATE. It must cross an export/import unchanged: carrying it is what keeps
	// `InitGenesis` from resetting the reserve to its genesis value and the epoch to 0. Without it, a
	// single export/import round trip refills an already-spent reserve (the same release schedule is
	// paid out twice); erases the unclaimed work and availability pools, so subsidies owed to miners
	// vanish while the coins backing them are counted back as reserve; and leaves `last_epoch = 0`
	// against an already-high height, which fires an epoch on the first block.
	//
	// The field is NULLABLE ON PURPOSE, and that is the whole subtlety: proto3 does not distinguish
	// "absent" from "zero" on a scalar, and a legitimately exhausted reserve IS zero. An optional
	// message makes the distinction legible — ABSENT means a fresh chain and the engine is bootstrapped;
	// PRESENT means a resumption and the state is restored exactly, zeros included.
	State *EmissionState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_60fdc78118f424e8, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetState() *EmissionState {
	if m != nil {
		return m.State
	}
	return nil
}

// EmissionState — the engine state, as it must survive an export/import.
type EmissionState struct {
	Reserve      uint64 `protobuf:"varint,1,opt,name=reserve,proto3" json:"reserve,omitempty"`
	WorkPool     uint64 `protobuf:"varint,2,opt,name=work_pool,json=workPool,proto3" json:"work_pool,omitempty"`
	AvailPool    uint64 `protobuf:"varint,3,opt,name=avail_pool,json=availPool,proto3" json:"avail_pool,omitempty"`
	SecurityPool uint64 `protobuf:"varint,4,opt,name=security_pool,json=securityPool,proto3" json:"security_pool,omitempty"`
	LastEpoch    uint64 `protobuf:"varint,5,opt,name=last_epoch,json=lastEpoch,proto3" json:"last_epoch,omitempty"`
	LastSupply   uint64 `protobuf:"varint,6,opt,name=last_supply,json=lastSupply,proto3" json:"last_supply,omitempty"`
}

func (m *EmissionState) Reset()         { *m = EmissionState{} }
func (m *EmissionState) String() string { return proto.CompactTextString(m) }
func (*EmissionState) ProtoMessage()    {}
func (*EmissionState) Descriptor() ([]byte, []int) {
	return fileDescriptor_60fdc78118f424e8, []int{1}
}
func (m *EmissionState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmissionState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EmissionState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EmissionState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmissionState.Merge(m, src)
}
func (m *EmissionState) XXX_Size() int {
	return m.Size()
}
func (m *EmissionState) XXX_DiscardUnknown() {
	xxx_messageInfo_EmissionState.DiscardUnknown(m)
}

var xxx_messageInfo_EmissionState proto.InternalMessageInfo

func (m *EmissionState) GetReserve() uint64 {
	if m != nil {
		return m.Reserve
	}
	return 0
}

func (m *EmissionState) GetWorkPool() uint64 {
	if m != nil {
		return m.WorkPool
	}
	return 0
}

func (m *EmissionState) GetAvailPool() uint64 {
	if m != nil {
		return m.AvailPool
	}
	return 0
}

func (m *EmissionState) GetSecurityPool() uint64 {
	if m != nil {
		return m.SecurityPool
	}
	return 0
}

func (m *EmissionState) GetLastEpoch() uint64 {
	if m != nil {
		return m.LastEpoch
	}
	return 0
}

func (m *EmissionState) GetLastSupply() uint64 {
	if m != nil {
		return m.LastSupply
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "dendra.emission.v1.GenesisState")
	proto.RegisterType((*EmissionState)(nil), "dendra.emission.v1.EmissionState")
}

func init() { proto.RegisterFile("dendra/emission/v1/genesis.proto", fileDescriptor_60fdc78118f424e8) }

var fileDescriptor_60fdc78118f424e8 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xbf, 0x6e, 0xe2, 0x30,
	0x18, 0x8f, 0xef, 0x80, 0x3b, 0x0c, 0x0c, 0x67, 0xdd, 0x10, 0xe5, 0x74, 0x81, 0xe3, 0x96, 0xd3,
	0x49, 0x17, 0x8b, 0xeb, 0xd0, 0xa9, 0x1d, 0x50, 0x51, 0xb7, 0x0a, 0x85, 0xa5, 0xea, 0x82, 0x4c,
	0xb0, 0x82, 0xd5, 0x24, 0x8e, 0x62, 0x93, 0x96, 0x17, 0xe8, 0xdc, 0xc7, 0xe8, 0xd8, 0xc7, 0x40,
	0x9d, 0x18, 0x3b, 0x55, 0x15, 0x0c, 0x7d, 0x8d, 0x2a, 0x9f, 0x13, 0x55, 0x55, 0x59, 0xac, 0xcf,
	0xbf, 0xbf, 0x96, 0x3f, 0xdc, 0x9b, 0xf3, 0x64, 0x9e, 0x31, 0xca, 0x63, 0xa1, 0x94, 0x90, 0x09,
	0xcd, 0x07, 0x34, 0xe4, 0x09, 0x57, 0x42, 0x79, 0x69, 0x26, 0xb5, 0x24, 0xc4, 0x28, 0xbc, 0x4a,
	0xe1, 0xe5, 0x03, 0xe7, 0x1b, 0x8b, 0x45, 0x22, 0x29, 0x9c, 0x46, 0xe6, 0x74, 0xf7, 0x04, 0xa5,
	0x2c, 0x63, 0x71, 0x99, 0xe3, 0x7c, 0x0f, 0x65, 0x28, 0x61, 0xa4, 0xc5, 0x64, 0xd0, 0xfe, 0x0d,
	0xc2, 0xed, 0x53, 0xd3, 0x37, 0xd1, 0x4c, 0x73, 0x72, 0x84, 0x1b, 0xc6, 0x66, 0xa3, 0x1e, 0xfa,
	0xd3, 0xfa, 0xef, 0x78, 0x1f, 0xfb, 0xbd, 0x31, 0x28, 0x86, 0xcd, 0xf5, 0x53, 0xd7, 0xba, 0x7b,
	0xb9, 0xff, 0x8b, 0xfc, 0xd2, 0x44, 0x0e, 0x71, 0x5d, 0x15, 0x39, 0xf6, 0x27, 0x70, 0xff, 0xda,
	0xe7, 0x1e, 0x95, 0x33, 0x14, 0xfa, 0x46, 0xdf, 0x7f, 0x40, 0xb8, 0xf3, 0x8e, 0x20, 0x36, 0xfe,
	0x92, 0x71, 0xc5, 0xb3, 0x9c, 0xc3, 0x53, 0x6a, 0x7e, 0x75, 0x25, 0x3f, 0x70, 0xf3, 0x4a, 0x66,
	0x97, 0xd3, 0x54, 0xca, 0x08, 0x8a, 0x6a, 0xfe, 0xd7, 0x02, 0x18, 0x4b, 0x19, 0x91, 0x9f, 0x18,
	0xb3, 0x9c, 0x89, 0xc8, 0xb0, 0x9f, 0x81, 0x6d, 0x02, 0x02, 0xf4, 0x6f, 0xdc, 0x51, 0x3c, 0x58,
	0x66, 0x42, 0xaf, 0x8c, 0xa2, 0x06, 0x8a, 0x76, 0x05, 0x56, 0x19, 0x11, 0x53, 0x7a, 0xca, 0x53,
	0x19, 0x2c, 0xec, 0xba, 0xc9, 0x28, 0x90, 0x51, 0x01, 0x90, 0x2e, 0x6e, 0x01, 0xad, 0x96, 0x69,
	0x1a, 0xad, 0xec, 0x06, 0xf0, 0xe0, 0x98, 0x00, 0x32, 0x3c, 0x5f, 0x6f, 0x5d, 0xb4, 0xd9, 0xba,
	0xe8, 0x79, 0xeb, 0xa2, 0xdb, 0x9d, 0x6b, 0x6d, 0x76, 0xae, 0xf5, 0xb8, 0x73, 0xad, 0x8b, 0xe3,
	0x50, 0xe8, 0xc5, 0x72, 0xe6, 0x05, 0x32, 0xa6, 0x27, 0xf0, 0x35, 0x67, 0x5c, 0x17, 0x6f, 0xa7,
	0xe6, 0xa3, 0xfe, 0x25, 0xe5, 0x35, 0x58, 0x30, 0x91, 0xd0, 0xeb, 0xb7, 0x7d, 0xea, 0x55, 0xca,
	0xd5, 0xac, 0x01, 0x6b, 0x3b, 0x78, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x97, 0x10, 0x66, 0x3a, 0x38,
	0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.State != nil {
		{
			size, err := m.State.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EmissionState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmissionState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EmissionState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastSupply != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LastSupply))
		i--
		dAtA[i] = 0x30
	}
	if m.LastEpoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LastEpoch))
		i--
		dAtA[i] = 0x28
	}
	if m.SecurityPool != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SecurityPool))
		i--
		dAtA[i] = 0x20
	}
	if m.AvailPool != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.AvailPool))
		i--
		dAtA[i] = 0x18
	}
	if m.WorkPool != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.WorkPool))
		i--
		dAtA[i] = 0x10
	}
	if m.Reserve != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Reserve))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.State != nil {
		l = m.State.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *EmissionState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Reserve != 0 {
		n += 1 + sovGenesis(uint64(m.Reserve))
	}
	if m.WorkPool != 0 {
		n += 1 + sovGenesis(uint64(m.WorkPool))
	}
	if m.AvailPool != 0 {
		n += 1 + sovGenesis(uint64(m.AvailPool))
	}
	if m.SecurityPool != 0 {
		n += 1 + sovGenesis(uint64(m.SecurityPool))
	}
	if m.LastEpoch != 0 {
		n += 1 + sovGenesis(uint64(m.LastEpoch))
	}
	if m.LastSupply != 0 {
		n += 1 + sovGenesis(uint64(m.LastSupply))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.State == nil {
				m.State = &EmissionState{}
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmissionState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmissionState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmissionState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reserve", wireType)
			}
			m.Reserve = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reserve |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkPool", wireType)
			}
			m.WorkPool = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WorkPool |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailPool", wireType)
			}
			m.AvailPool = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvailPool |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecurityPool", wireType)
			}
			m.SecurityPool = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecurityPool |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastEpoch", wireType)
			}
			m.LastEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastSupply", wireType)
			}
			m.LastSupply = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastSupply |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
